apiVersion: v1
kind: Secret
metadata:
  name: template-secrets
  namespace: go-astro-template
type: Opaque
stringData:
  postgresDsn: ""
  redisAddr: ""
  redisPassword: ""
  smtpHost: ""
  smtpUsername: ""
  smtpPassword: ""
  r2AccountId: ""
  r2AccessKeyId: ""
  r2SecretAccessKey: ""
  r2Bucket: ""
  r2Endpoint: ""
  r2PublicBaseUrl: ""
