// Code generated by ent, DO NOT EDIT.

package teaminvite

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldUpdatedAt, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldTeamID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldEmail, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldToken, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldExpiresAt, v))
}

// InvitedBy applies equality check predicate on the "invited_by" field. It's identical to InvitedByEQ.
func InvitedBy(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldInvitedBy, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContainsFold(FieldTenantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLTE(FieldUpdatedAt, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNotIn(FieldTeamID, vs...))
}

// TeamIDGT applies the GT predicate on the "team_id" field.
func TeamIDGT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGT(FieldTeamID, v))
}

// TeamIDGTE applies the GTE predicate on the "team_id" field.
func TeamIDGTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGTE(FieldTeamID, v))
}

// TeamIDLT applies the LT predicate on the "team_id" field.
func TeamIDLT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLT(FieldTeamID, v))
}

// TeamIDLTE applies the LTE predicate on the "team_id" field.
func TeamIDLTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLTE(FieldTeamID, v))
}

// TeamIDContains applies the Contains predicate on the "team_id" field.
func TeamIDContains(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContains(FieldTeamID, v))
}

// TeamIDHasPrefix applies the HasPrefix predicate on the "team_id" field.
func TeamIDHasPrefix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasPrefix(FieldTeamID, v))
}

// TeamIDHasSuffix applies the HasSuffix predicate on the "team_id" field.
func TeamIDHasSuffix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasSuffix(FieldTeamID, v))
}

// TeamIDEqualFold applies the EqualFold predicate on the "team_id" field.
func TeamIDEqualFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEqualFold(FieldTeamID, v))
}

// TeamIDContainsFold applies the ContainsFold predicate on the "team_id" field.
func TeamIDContainsFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContainsFold(FieldTeamID, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContainsFold(FieldEmail, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContainsFold(FieldToken, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLTE(FieldExpiresAt, v))
}

// InvitedByEQ applies the EQ predicate on the "invited_by" field.
func InvitedByEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEQ(FieldInvitedBy, v))
}

// InvitedByNEQ applies the NEQ predicate on the "invited_by" field.
func InvitedByNEQ(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNEQ(FieldInvitedBy, v))
}

// InvitedByIn applies the In predicate on the "invited_by" field.
func InvitedByIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldIn(FieldInvitedBy, vs...))
}

// InvitedByNotIn applies the NotIn predicate on the "invited_by" field.
func InvitedByNotIn(vs ...string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldNotIn(FieldInvitedBy, vs...))
}

// InvitedByGT applies the GT predicate on the "invited_by" field.
func InvitedByGT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGT(FieldInvitedBy, v))
}

// InvitedByGTE applies the GTE predicate on the "invited_by" field.
func InvitedByGTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldGTE(FieldInvitedBy, v))
}

// InvitedByLT applies the LT predicate on the "invited_by" field.
func InvitedByLT(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLT(FieldInvitedBy, v))
}

// InvitedByLTE applies the LTE predicate on the "invited_by" field.
func InvitedByLTE(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldLTE(FieldInvitedBy, v))
}

// InvitedByContains applies the Contains predicate on the "invited_by" field.
func InvitedByContains(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContains(FieldInvitedBy, v))
}

// InvitedByHasPrefix applies the HasPrefix predicate on the "invited_by" field.
func InvitedByHasPrefix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasPrefix(FieldInvitedBy, v))
}

// InvitedByHasSuffix applies the HasSuffix predicate on the "invited_by" field.
func InvitedByHasSuffix(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldHasSuffix(FieldInvitedBy, v))
}

// InvitedByEqualFold applies the EqualFold predicate on the "invited_by" field.
func InvitedByEqualFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldEqualFold(FieldInvitedBy, v))
}

// InvitedByContainsFold applies the ContainsFold predicate on the "invited_by" field.
func InvitedByContainsFold(v string) predicate.TeamInvite {
	return predicate.TeamInvite(sql.FieldContainsFold(FieldInvitedBy, v))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamInvite {
	return predicate.TeamInvite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamInvite {
	return predicate.TeamInvite(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamInvite) predicate.TeamInvite {
	return predicate.TeamInvite(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamInvite) predicate.TeamInvite {
	return predicate.TeamInvite(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamInvite) predicate.TeamInvite {
	return predicate.TeamInvite(sql.NotPredicates(p))
}
