apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  postgresDsn: {{ .Values.secrets.postgresDsn | quote }}
  redisAddr: {{ .Values.secrets.redisAddr | quote }}
  redisPassword: {{ .Values.secrets.redisPassword | quote }}
  smtpHost: {{ .Values.secrets.smtpHost | quote }}
  smtpUsername: {{ .Values.secrets.smtpUsername | quote }}
  smtpPassword: {{ .Values.secrets.smtpPassword | quote }}
  r2AccountId: {{ .Values.secrets.r2AccountId | quote }}
  r2AccessKeyId: {{ .Values.secrets.r2AccessKeyId | quote }}
  r2SecretAccessKey: {{ .Values.secrets.r2SecretAccessKey | quote }}
  r2Bucket: {{ .Values.secrets.r2Bucket | quote }}
  r2Endpoint: {{ .Values.secrets.r2Endpoint | quote }}
  r2PublicBaseUrl: {{ .Values.secrets.r2PublicBaseUrl | quote }}
