apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      serviceAccountName: {{ default (default .Release.Name .Values.global.serviceAccountName) .Values.web.serviceAccountName }}
      containers:
        - name: web
          image: {{ .Values.web.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4321
          resources:
{{ toYaml .Values.web.resources | indent 12 }}
