// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/night/go-astro-template/apps/api/ent/agentconversation"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
)

// AgentConversationDelete is the builder for deleting a AgentConversation entity.
type AgentConversationDelete struct {
	config
	hooks    []Hook
	mutation *AgentConversationMutation
}

// Where appends a list predicates to the AgentConversationDelete builder.
func (_d *AgentConversationDelete) Where(ps ...predicate.AgentConversation) *AgentConversationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgentConversationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentConversationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgentConversationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agentconversation.Table, sqlgraph.NewFieldSpec(agentconversation.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgentConversationDeleteOne is the builder for deleting a single AgentConversation entity.
type AgentConversationDeleteOne struct {
	_d *AgentConversationDelete
}

// Where appends a list predicates to the AgentConversationDelete builder.
func (_d *AgentConversationDeleteOne) Where(ps ...predicate.AgentConversation) *AgentConversationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgentConversationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agentconversation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentConversationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
