// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/night/go-astro-template/apps/api/ent/agentconversation"
	"github.com/night/go-astro-template/apps/api/ent/agentmessage"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
	"github.com/night/go-astro-template/apps/api/ent/user"
)

// AgentConversationUpdate is the builder for updating AgentConversation entities.
type AgentConversationUpdate struct {
	config
	hooks    []Hook
	mutation *AgentConversationMutation
}

// Where appends a list predicates to the AgentConversationUpdate builder.
func (_u *AgentConversationUpdate) Where(ps ...predicate.AgentConversation) *AgentConversationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentConversationUpdate) SetUpdatedAt(v time.Time) *AgentConversationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AgentConversationUpdate) SetUserID(v string) *AgentConversationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AgentConversationUpdate) SetNillableUserID(v *string) *AgentConversationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *AgentConversationUpdate) SetTitle(v string) *AgentConversationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AgentConversationUpdate) SetNillableTitle(v *string) *AgentConversationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AgentConversationUpdate) SetUser(v *User) *AgentConversationUpdate {
	return _u.SetUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the AgentMessage entity by IDs.
func (_u *AgentConversationUpdate) AddMessageIDs(ids ...string) *AgentConversationUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the AgentMessage entity.
func (_u *AgentConversationUpdate) AddMessages(v ...*AgentMessage) *AgentConversationUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the AgentConversationMutation object of the builder.
func (_u *AgentConversationUpdate) Mutation() *AgentConversationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AgentConversationUpdate) ClearUser() *AgentConversationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearMessages clears all "messages" edges to the AgentMessage entity.
func (_u *AgentConversationUpdate) ClearMessages() *AgentConversationUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to AgentMessage entities by IDs.
func (_u *AgentConversationUpdate) RemoveMessageIDs(ids ...string) *AgentConversationUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to AgentMessage entities.
func (_u *AgentConversationUpdate) RemoveMessages(v ...*AgentMessage) *AgentConversationUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentConversationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentConversationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentConversationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentConversationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentconversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentConversationUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := agentconversation.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "AgentConversation.user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentConversation.user"`)
	}
	return nil
}

func (_u *AgentConversationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentconversation.Table, agentconversation.Columns, sqlgraph.NewFieldSpec(agentconversation.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentconversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(agentconversation.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentconversation.UserTable,
			Columns: []string{agentconversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentconversation.UserTable,
			Columns: []string{agentconversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentconversation.MessagesTable,
			Columns: []string{agentconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentmessage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentconversation.MessagesTable,
			Columns: []string{agentconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentconversation.MessagesTable,
			Columns: []string{agentconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentConversationUpdateOne is the builder for updating a single AgentConversation entity.
type AgentConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentConversationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentConversationUpdateOne) SetUpdatedAt(v time.Time) *AgentConversationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AgentConversationUpdateOne) SetUserID(v string) *AgentConversationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AgentConversationUpdateOne) SetNillableUserID(v *string) *AgentConversationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *AgentConversationUpdateOne) SetTitle(v string) *AgentConversationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AgentConversationUpdateOne) SetNillableTitle(v *string) *AgentConversationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AgentConversationUpdateOne) SetUser(v *User) *AgentConversationUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the AgentMessage entity by IDs.
func (_u *AgentConversationUpdateOne) AddMessageIDs(ids ...string) *AgentConversationUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the AgentMessage entity.
func (_u *AgentConversationUpdateOne) AddMessages(v ...*AgentMessage) *AgentConversationUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the AgentConversationMutation object of the builder.
func (_u *AgentConversationUpdateOne) Mutation() *AgentConversationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AgentConversationUpdateOne) ClearUser() *AgentConversationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearMessages clears all "messages" edges to the AgentMessage entity.
func (_u *AgentConversationUpdateOne) ClearMessages() *AgentConversationUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to AgentMessage entities by IDs.
func (_u *AgentConversationUpdateOne) RemoveMessageIDs(ids ...string) *AgentConversationUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to AgentMessage entities.
func (_u *AgentConversationUpdateOne) RemoveMessages(v ...*AgentMessage) *AgentConversationUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the AgentConversationUpdate builder.
func (_u *AgentConversationUpdateOne) Where(ps ...predicate.AgentConversation) *AgentConversationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentConversationUpdateOne) Select(field string, fields ...string) *AgentConversationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentConversation entity.
func (_u *AgentConversationUpdateOne) Save(ctx context.Context) (*AgentConversation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentConversationUpdateOne) SaveX(ctx context.Context) *AgentConversation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentConversationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentConversationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentconversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentConversationUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := agentconversation.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "AgentConversation.user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentConversation.user"`)
	}
	return nil
}

func (_u *AgentConversationUpdateOne) sqlSave(ctx context.Context) (_node *AgentConversation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentconversation.Table, agentconversation.Columns, sqlgraph.NewFieldSpec(agentconversation.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentConversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentconversation.FieldID)
		for _, f := range fields {
			if !agentconversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentconversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentconversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(agentconversation.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentconversation.UserTable,
			Columns: []string{agentconversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentconversation.UserTable,
			Columns: []string{agentconversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentconversation.MessagesTable,
			Columns: []string{agentconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentmessage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentconversation.MessagesTable,
			Columns: []string{agentconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentconversation.MessagesTable,
			Columns: []string{agentconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentConversation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
