// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/night/go-astro-template/apps/api/ent/blogpost"
	"github.com/night/go-astro-template/apps/api/ent/blogpreviewtoken"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
)

// BlogPreviewTokenUpdate is the builder for updating BlogPreviewToken entities.
type BlogPreviewTokenUpdate struct {
	config
	hooks    []Hook
	mutation *BlogPreviewTokenMutation
}

// Where appends a list predicates to the BlogPreviewTokenUpdate builder.
func (_u *BlogPreviewTokenUpdate) Where(ps ...predicate.BlogPreviewToken) *BlogPreviewTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlogPreviewTokenUpdate) SetUpdatedAt(v time.Time) *BlogPreviewTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBlogPostID sets the "blog_post_id" field.
func (_u *BlogPreviewTokenUpdate) SetBlogPostID(v string) *BlogPreviewTokenUpdate {
	_u.mutation.SetBlogPostID(v)
	return _u
}

// SetNillableBlogPostID sets the "blog_post_id" field if the given value is not nil.
func (_u *BlogPreviewTokenUpdate) SetNillableBlogPostID(v *string) *BlogPreviewTokenUpdate {
	if v != nil {
		_u.SetBlogPostID(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *BlogPreviewTokenUpdate) SetToken(v string) *BlogPreviewTokenUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *BlogPreviewTokenUpdate) SetNillableToken(v *string) *BlogPreviewTokenUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BlogPreviewTokenUpdate) SetLanguage(v string) *BlogPreviewTokenUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BlogPreviewTokenUpdate) SetNillableLanguage(v *string) *BlogPreviewTokenUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BlogPreviewTokenUpdate) SetExpiresAt(v time.Time) *BlogPreviewTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BlogPreviewTokenUpdate) SetNillableExpiresAt(v *time.Time) *BlogPreviewTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetBlogPost sets the "blog_post" edge to the BlogPost entity.
func (_u *BlogPreviewTokenUpdate) SetBlogPost(v *BlogPost) *BlogPreviewTokenUpdate {
	return _u.SetBlogPostID(v.ID)
}

// Mutation returns the BlogPreviewTokenMutation object of the builder.
func (_u *BlogPreviewTokenUpdate) Mutation() *BlogPreviewTokenMutation {
	return _u.mutation
}

// ClearBlogPost clears the "blog_post" edge to the BlogPost entity.
func (_u *BlogPreviewTokenUpdate) ClearBlogPost() *BlogPreviewTokenUpdate {
	_u.mutation.ClearBlogPost()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BlogPreviewTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlogPreviewTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BlogPreviewTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlogPreviewTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlogPreviewTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blogpreviewtoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BlogPreviewTokenUpdate) check() error {
	if v, ok := _u.mutation.BlogPostID(); ok {
		if err := blogpreviewtoken.BlogPostIDValidator(v); err != nil {
			return &ValidationError{Name: "blog_post_id", err: fmt.Errorf(`ent: validator failed for field "BlogPreviewToken.blog_post_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := blogpreviewtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "BlogPreviewToken.token": %w`, err)}
		}
	}
	if _u.mutation.BlogPostCleared() && len(_u.mutation.BlogPostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BlogPreviewToken.blog_post"`)
	}
	return nil
}

func (_u *BlogPreviewTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blogpreviewtoken.Table, blogpreviewtoken.Columns, sqlgraph.NewFieldSpec(blogpreviewtoken.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blogpreviewtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(blogpreviewtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(blogpreviewtoken.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(blogpreviewtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.BlogPostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogpreviewtoken.BlogPostTable,
			Columns: []string{blogpreviewtoken.BlogPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlogPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogpreviewtoken.BlogPostTable,
			Columns: []string{blogpreviewtoken.BlogPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blogpreviewtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BlogPreviewTokenUpdateOne is the builder for updating a single BlogPreviewToken entity.
type BlogPreviewTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlogPreviewTokenMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlogPreviewTokenUpdateOne) SetUpdatedAt(v time.Time) *BlogPreviewTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBlogPostID sets the "blog_post_id" field.
func (_u *BlogPreviewTokenUpdateOne) SetBlogPostID(v string) *BlogPreviewTokenUpdateOne {
	_u.mutation.SetBlogPostID(v)
	return _u
}

// SetNillableBlogPostID sets the "blog_post_id" field if the given value is not nil.
func (_u *BlogPreviewTokenUpdateOne) SetNillableBlogPostID(v *string) *BlogPreviewTokenUpdateOne {
	if v != nil {
		_u.SetBlogPostID(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *BlogPreviewTokenUpdateOne) SetToken(v string) *BlogPreviewTokenUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *BlogPreviewTokenUpdateOne) SetNillableToken(v *string) *BlogPreviewTokenUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BlogPreviewTokenUpdateOne) SetLanguage(v string) *BlogPreviewTokenUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BlogPreviewTokenUpdateOne) SetNillableLanguage(v *string) *BlogPreviewTokenUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BlogPreviewTokenUpdateOne) SetExpiresAt(v time.Time) *BlogPreviewTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BlogPreviewTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *BlogPreviewTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetBlogPost sets the "blog_post" edge to the BlogPost entity.
func (_u *BlogPreviewTokenUpdateOne) SetBlogPost(v *BlogPost) *BlogPreviewTokenUpdateOne {
	return _u.SetBlogPostID(v.ID)
}

// Mutation returns the BlogPreviewTokenMutation object of the builder.
func (_u *BlogPreviewTokenUpdateOne) Mutation() *BlogPreviewTokenMutation {
	return _u.mutation
}

// ClearBlogPost clears the "blog_post" edge to the BlogPost entity.
func (_u *BlogPreviewTokenUpdateOne) ClearBlogPost() *BlogPreviewTokenUpdateOne {
	_u.mutation.ClearBlogPost()
	return _u
}

// Where appends a list predicates to the BlogPreviewTokenUpdate builder.
func (_u *BlogPreviewTokenUpdateOne) Where(ps ...predicate.BlogPreviewToken) *BlogPreviewTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BlogPreviewTokenUpdateOne) Select(field string, fields ...string) *BlogPreviewTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BlogPreviewToken entity.
func (_u *BlogPreviewTokenUpdateOne) Save(ctx context.Context) (*BlogPreviewToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlogPreviewTokenUpdateOne) SaveX(ctx context.Context) *BlogPreviewToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BlogPreviewTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlogPreviewTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlogPreviewTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blogpreviewtoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BlogPreviewTokenUpdateOne) check() error {
	if v, ok := _u.mutation.BlogPostID(); ok {
		if err := blogpreviewtoken.BlogPostIDValidator(v); err != nil {
			return &ValidationError{Name: "blog_post_id", err: fmt.Errorf(`ent: validator failed for field "BlogPreviewToken.blog_post_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := blogpreviewtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "BlogPreviewToken.token": %w`, err)}
		}
	}
	if _u.mutation.BlogPostCleared() && len(_u.mutation.BlogPostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BlogPreviewToken.blog_post"`)
	}
	return nil
}

func (_u *BlogPreviewTokenUpdateOne) sqlSave(ctx context.Context) (_node *BlogPreviewToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blogpreviewtoken.Table, blogpreviewtoken.Columns, sqlgraph.NewFieldSpec(blogpreviewtoken.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BlogPreviewToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blogpreviewtoken.FieldID)
		for _, f := range fields {
			if !blogpreviewtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blogpreviewtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blogpreviewtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(blogpreviewtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(blogpreviewtoken.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(blogpreviewtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.BlogPostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogpreviewtoken.BlogPostTable,
			Columns: []string{blogpreviewtoken.BlogPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlogPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogpreviewtoken.BlogPostTable,
			Columns: []string{blogpreviewtoken.BlogPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BlogPreviewToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blogpreviewtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
