// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/night/go-astro-template/apps/api/ent/blogpost"
	"github.com/night/go-astro-template/apps/api/ent/blogtranslation"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
)

// BlogTranslationUpdate is the builder for updating BlogTranslation entities.
type BlogTranslationUpdate struct {
	config
	hooks    []Hook
	mutation *BlogTranslationMutation
}

// Where appends a list predicates to the BlogTranslationUpdate builder.
func (_u *BlogTranslationUpdate) Where(ps ...predicate.BlogTranslation) *BlogTranslationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlogTranslationUpdate) SetUpdatedAt(v time.Time) *BlogTranslationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBlogPostID sets the "blog_post_id" field.
func (_u *BlogTranslationUpdate) SetBlogPostID(v string) *BlogTranslationUpdate {
	_u.mutation.SetBlogPostID(v)
	return _u
}

// SetNillableBlogPostID sets the "blog_post_id" field if the given value is not nil.
func (_u *BlogTranslationUpdate) SetNillableBlogPostID(v *string) *BlogTranslationUpdate {
	if v != nil {
		_u.SetBlogPostID(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BlogTranslationUpdate) SetLanguage(v string) *BlogTranslationUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BlogTranslationUpdate) SetNillableLanguage(v *string) *BlogTranslationUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BlogTranslationUpdate) SetTitle(v string) *BlogTranslationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BlogTranslationUpdate) SetNillableTitle(v *string) *BlogTranslationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetExcerpt sets the "excerpt" field.
func (_u *BlogTranslationUpdate) SetExcerpt(v string) *BlogTranslationUpdate {
	_u.mutation.SetExcerpt(v)
	return _u
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (_u *BlogTranslationUpdate) SetNillableExcerpt(v *string) *BlogTranslationUpdate {
	if v != nil {
		_u.SetExcerpt(*v)
	}
	return _u
}

// ClearExcerpt clears the value of the "excerpt" field.
func (_u *BlogTranslationUpdate) ClearExcerpt() *BlogTranslationUpdate {
	_u.mutation.ClearExcerpt()
	return _u
}

// SetContent sets the "content" field.
func (_u *BlogTranslationUpdate) SetContent(v string) *BlogTranslationUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *BlogTranslationUpdate) SetNillableContent(v *string) *BlogTranslationUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMetaTitle sets the "meta_title" field.
func (_u *BlogTranslationUpdate) SetMetaTitle(v string) *BlogTranslationUpdate {
	_u.mutation.SetMetaTitle(v)
	return _u
}

// SetNillableMetaTitle sets the "meta_title" field if the given value is not nil.
func (_u *BlogTranslationUpdate) SetNillableMetaTitle(v *string) *BlogTranslationUpdate {
	if v != nil {
		_u.SetMetaTitle(*v)
	}
	return _u
}

// ClearMetaTitle clears the value of the "meta_title" field.
func (_u *BlogTranslationUpdate) ClearMetaTitle() *BlogTranslationUpdate {
	_u.mutation.ClearMetaTitle()
	return _u
}

// SetMetaDescription sets the "meta_description" field.
func (_u *BlogTranslationUpdate) SetMetaDescription(v string) *BlogTranslationUpdate {
	_u.mutation.SetMetaDescription(v)
	return _u
}

// SetNillableMetaDescription sets the "meta_description" field if the given value is not nil.
func (_u *BlogTranslationUpdate) SetNillableMetaDescription(v *string) *BlogTranslationUpdate {
	if v != nil {
		_u.SetMetaDescription(*v)
	}
	return _u
}

// ClearMetaDescription clears the value of the "meta_description" field.
func (_u *BlogTranslationUpdate) ClearMetaDescription() *BlogTranslationUpdate {
	_u.mutation.ClearMetaDescription()
	return _u
}

// SetKeywords sets the "keywords" field.
func (_u *BlogTranslationUpdate) SetKeywords(v string) *BlogTranslationUpdate {
	_u.mutation.SetKeywords(v)
	return _u
}

// SetNillableKeywords sets the "keywords" field if the given value is not nil.
func (_u *BlogTranslationUpdate) SetNillableKeywords(v *string) *BlogTranslationUpdate {
	if v != nil {
		_u.SetKeywords(*v)
	}
	return _u
}

// ClearKeywords clears the value of the "keywords" field.
func (_u *BlogTranslationUpdate) ClearKeywords() *BlogTranslationUpdate {
	_u.mutation.ClearKeywords()
	return _u
}

// SetBlogPost sets the "blog_post" edge to the BlogPost entity.
func (_u *BlogTranslationUpdate) SetBlogPost(v *BlogPost) *BlogTranslationUpdate {
	return _u.SetBlogPostID(v.ID)
}

// Mutation returns the BlogTranslationMutation object of the builder.
func (_u *BlogTranslationUpdate) Mutation() *BlogTranslationMutation {
	return _u.mutation
}

// ClearBlogPost clears the "blog_post" edge to the BlogPost entity.
func (_u *BlogTranslationUpdate) ClearBlogPost() *BlogTranslationUpdate {
	_u.mutation.ClearBlogPost()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BlogTranslationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlogTranslationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BlogTranslationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlogTranslationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlogTranslationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blogtranslation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BlogTranslationUpdate) check() error {
	if v, ok := _u.mutation.BlogPostID(); ok {
		if err := blogtranslation.BlogPostIDValidator(v); err != nil {
			return &ValidationError{Name: "blog_post_id", err: fmt.Errorf(`ent: validator failed for field "BlogTranslation.blog_post_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := blogtranslation.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "BlogTranslation.language": %w`, err)}
		}
	}
	if _u.mutation.BlogPostCleared() && len(_u.mutation.BlogPostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BlogTranslation.blog_post"`)
	}
	return nil
}

func (_u *BlogTranslationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blogtranslation.Table, blogtranslation.Columns, sqlgraph.NewFieldSpec(blogtranslation.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blogtranslation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(blogtranslation.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(blogtranslation.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Excerpt(); ok {
		_spec.SetField(blogtranslation.FieldExcerpt, field.TypeString, value)
	}
	if _u.mutation.ExcerptCleared() {
		_spec.ClearField(blogtranslation.FieldExcerpt, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(blogtranslation.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaTitle(); ok {
		_spec.SetField(blogtranslation.FieldMetaTitle, field.TypeString, value)
	}
	if _u.mutation.MetaTitleCleared() {
		_spec.ClearField(blogtranslation.FieldMetaTitle, field.TypeString)
	}
	if value, ok := _u.mutation.MetaDescription(); ok {
		_spec.SetField(blogtranslation.FieldMetaDescription, field.TypeString, value)
	}
	if _u.mutation.MetaDescriptionCleared() {
		_spec.ClearField(blogtranslation.FieldMetaDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Keywords(); ok {
		_spec.SetField(blogtranslation.FieldKeywords, field.TypeString, value)
	}
	if _u.mutation.KeywordsCleared() {
		_spec.ClearField(blogtranslation.FieldKeywords, field.TypeString)
	}
	if _u.mutation.BlogPostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogtranslation.BlogPostTable,
			Columns: []string{blogtranslation.BlogPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlogPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogtranslation.BlogPostTable,
			Columns: []string{blogtranslation.BlogPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blogtranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BlogTranslationUpdateOne is the builder for updating a single BlogTranslation entity.
type BlogTranslationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlogTranslationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlogTranslationUpdateOne) SetUpdatedAt(v time.Time) *BlogTranslationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBlogPostID sets the "blog_post_id" field.
func (_u *BlogTranslationUpdateOne) SetBlogPostID(v string) *BlogTranslationUpdateOne {
	_u.mutation.SetBlogPostID(v)
	return _u
}

// SetNillableBlogPostID sets the "blog_post_id" field if the given value is not nil.
func (_u *BlogTranslationUpdateOne) SetNillableBlogPostID(v *string) *BlogTranslationUpdateOne {
	if v != nil {
		_u.SetBlogPostID(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BlogTranslationUpdateOne) SetLanguage(v string) *BlogTranslationUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BlogTranslationUpdateOne) SetNillableLanguage(v *string) *BlogTranslationUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BlogTranslationUpdateOne) SetTitle(v string) *BlogTranslationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BlogTranslationUpdateOne) SetNillableTitle(v *string) *BlogTranslationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetExcerpt sets the "excerpt" field.
func (_u *BlogTranslationUpdateOne) SetExcerpt(v string) *BlogTranslationUpdateOne {
	_u.mutation.SetExcerpt(v)
	return _u
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (_u *BlogTranslationUpdateOne) SetNillableExcerpt(v *string) *BlogTranslationUpdateOne {
	if v != nil {
		_u.SetExcerpt(*v)
	}
	return _u
}

// ClearExcerpt clears the value of the "excerpt" field.
func (_u *BlogTranslationUpdateOne) ClearExcerpt() *BlogTranslationUpdateOne {
	_u.mutation.ClearExcerpt()
	return _u
}

// SetContent sets the "content" field.
func (_u *BlogTranslationUpdateOne) SetContent(v string) *BlogTranslationUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *BlogTranslationUpdateOne) SetNillableContent(v *string) *BlogTranslationUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMetaTitle sets the "meta_title" field.
func (_u *BlogTranslationUpdateOne) SetMetaTitle(v string) *BlogTranslationUpdateOne {
	_u.mutation.SetMetaTitle(v)
	return _u
}

// SetNillableMetaTitle sets the "meta_title" field if the given value is not nil.
func (_u *BlogTranslationUpdateOne) SetNillableMetaTitle(v *string) *BlogTranslationUpdateOne {
	if v != nil {
		_u.SetMetaTitle(*v)
	}
	return _u
}

// ClearMetaTitle clears the value of the "meta_title" field.
func (_u *BlogTranslationUpdateOne) ClearMetaTitle() *BlogTranslationUpdateOne {
	_u.mutation.ClearMetaTitle()
	return _u
}

// SetMetaDescription sets the "meta_description" field.
func (_u *BlogTranslationUpdateOne) SetMetaDescription(v string) *BlogTranslationUpdateOne {
	_u.mutation.SetMetaDescription(v)
	return _u
}

// SetNillableMetaDescription sets the "meta_description" field if the given value is not nil.
func (_u *BlogTranslationUpdateOne) SetNillableMetaDescription(v *string) *BlogTranslationUpdateOne {
	if v != nil {
		_u.SetMetaDescription(*v)
	}
	return _u
}

// ClearMetaDescription clears the value of the "meta_description" field.
func (_u *BlogTranslationUpdateOne) ClearMetaDescription() *BlogTranslationUpdateOne {
	_u.mutation.ClearMetaDescription()
	return _u
}

// SetKeywords sets the "keywords" field.
func (_u *BlogTranslationUpdateOne) SetKeywords(v string) *BlogTranslationUpdateOne {
	_u.mutation.SetKeywords(v)
	return _u
}

// SetNillableKeywords sets the "keywords" field if the given value is not nil.
func (_u *BlogTranslationUpdateOne) SetNillableKeywords(v *string) *BlogTranslationUpdateOne {
	if v != nil {
		_u.SetKeywords(*v)
	}
	return _u
}

// ClearKeywords clears the value of the "keywords" field.
func (_u *BlogTranslationUpdateOne) ClearKeywords() *BlogTranslationUpdateOne {
	_u.mutation.ClearKeywords()
	return _u
}

// SetBlogPost sets the "blog_post" edge to the BlogPost entity.
func (_u *BlogTranslationUpdateOne) SetBlogPost(v *BlogPost) *BlogTranslationUpdateOne {
	return _u.SetBlogPostID(v.ID)
}

// Mutation returns the BlogTranslationMutation object of the builder.
func (_u *BlogTranslationUpdateOne) Mutation() *BlogTranslationMutation {
	return _u.mutation
}

// ClearBlogPost clears the "blog_post" edge to the BlogPost entity.
func (_u *BlogTranslationUpdateOne) ClearBlogPost() *BlogTranslationUpdateOne {
	_u.mutation.ClearBlogPost()
	return _u
}

// Where appends a list predicates to the BlogTranslationUpdate builder.
func (_u *BlogTranslationUpdateOne) Where(ps ...predicate.BlogTranslation) *BlogTranslationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BlogTranslationUpdateOne) Select(field string, fields ...string) *BlogTranslationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BlogTranslation entity.
func (_u *BlogTranslationUpdateOne) Save(ctx context.Context) (*BlogTranslation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlogTranslationUpdateOne) SaveX(ctx context.Context) *BlogTranslation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BlogTranslationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlogTranslationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlogTranslationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blogtranslation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BlogTranslationUpdateOne) check() error {
	if v, ok := _u.mutation.BlogPostID(); ok {
		if err := blogtranslation.BlogPostIDValidator(v); err != nil {
			return &ValidationError{Name: "blog_post_id", err: fmt.Errorf(`ent: validator failed for field "BlogTranslation.blog_post_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := blogtranslation.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "BlogTranslation.language": %w`, err)}
		}
	}
	if _u.mutation.BlogPostCleared() && len(_u.mutation.BlogPostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BlogTranslation.blog_post"`)
	}
	return nil
}

func (_u *BlogTranslationUpdateOne) sqlSave(ctx context.Context) (_node *BlogTranslation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blogtranslation.Table, blogtranslation.Columns, sqlgraph.NewFieldSpec(blogtranslation.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BlogTranslation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blogtranslation.FieldID)
		for _, f := range fields {
			if !blogtranslation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blogtranslation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blogtranslation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(blogtranslation.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(blogtranslation.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Excerpt(); ok {
		_spec.SetField(blogtranslation.FieldExcerpt, field.TypeString, value)
	}
	if _u.mutation.ExcerptCleared() {
		_spec.ClearField(blogtranslation.FieldExcerpt, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(blogtranslation.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaTitle(); ok {
		_spec.SetField(blogtranslation.FieldMetaTitle, field.TypeString, value)
	}
	if _u.mutation.MetaTitleCleared() {
		_spec.ClearField(blogtranslation.FieldMetaTitle, field.TypeString)
	}
	if value, ok := _u.mutation.MetaDescription(); ok {
		_spec.SetField(blogtranslation.FieldMetaDescription, field.TypeString, value)
	}
	if _u.mutation.MetaDescriptionCleared() {
		_spec.ClearField(blogtranslation.FieldMetaDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Keywords(); ok {
		_spec.SetField(blogtranslation.FieldKeywords, field.TypeString, value)
	}
	if _u.mutation.KeywordsCleared() {
		_spec.ClearField(blogtranslation.FieldKeywords, field.TypeString)
	}
	if _u.mutation.BlogPostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogtranslation.BlogPostTable,
			Columns: []string{blogtranslation.BlogPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlogPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogtranslation.BlogPostTable,
			Columns: []string{blogtranslation.BlogPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BlogTranslation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blogtranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
