// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/night/go-astro-template/apps/api/ent/blogpost"
	"github.com/night/go-astro-template/apps/api/ent/blogpreviewtoken"
)

// BlogPreviewTokenCreate is the builder for creating a BlogPreviewToken entity.
type BlogPreviewTokenCreate struct {
	config
	mutation *BlogPreviewTokenMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *BlogPreviewTokenCreate) SetTenantID(v string) *BlogPreviewTokenCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *BlogPreviewTokenCreate) SetNillableTenantID(v *string) *BlogPreviewTokenCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BlogPreviewTokenCreate) SetCreatedAt(v time.Time) *BlogPreviewTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BlogPreviewTokenCreate) SetNillableCreatedAt(v *time.Time) *BlogPreviewTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BlogPreviewTokenCreate) SetUpdatedAt(v time.Time) *BlogPreviewTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BlogPreviewTokenCreate) SetNillableUpdatedAt(v *time.Time) *BlogPreviewTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBlogPostID sets the "blog_post_id" field.
func (_c *BlogPreviewTokenCreate) SetBlogPostID(v string) *BlogPreviewTokenCreate {
	_c.mutation.SetBlogPostID(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *BlogPreviewTokenCreate) SetToken(v string) *BlogPreviewTokenCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetLanguage sets the "language" field.
func (_c *BlogPreviewTokenCreate) SetLanguage(v string) *BlogPreviewTokenCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *BlogPreviewTokenCreate) SetNillableLanguage(v *string) *BlogPreviewTokenCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *BlogPreviewTokenCreate) SetExpiresAt(v time.Time) *BlogPreviewTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *BlogPreviewTokenCreate) SetNillableExpiresAt(v *time.Time) *BlogPreviewTokenCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BlogPreviewTokenCreate) SetID(v string) *BlogPreviewTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BlogPreviewTokenCreate) SetNillableID(v *string) *BlogPreviewTokenCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetBlogPost sets the "blog_post" edge to the BlogPost entity.
func (_c *BlogPreviewTokenCreate) SetBlogPost(v *BlogPost) *BlogPreviewTokenCreate {
	return _c.SetBlogPostID(v.ID)
}

// Mutation returns the BlogPreviewTokenMutation object of the builder.
func (_c *BlogPreviewTokenCreate) Mutation() *BlogPreviewTokenMutation {
	return _c.mutation
}

// Save creates the BlogPreviewToken in the database.
func (_c *BlogPreviewTokenCreate) Save(ctx context.Context) (*BlogPreviewToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BlogPreviewTokenCreate) SaveX(ctx context.Context) *BlogPreviewToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogPreviewTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogPreviewTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BlogPreviewTokenCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := blogpreviewtoken.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := blogpreviewtoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := blogpreviewtoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := blogpreviewtoken.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		v := blogpreviewtoken.DefaultExpiresAt()
		_c.mutation.SetExpiresAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := blogpreviewtoken.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BlogPreviewTokenCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "BlogPreviewToken.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BlogPreviewToken.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BlogPreviewToken.updated_at"`)}
	}
	if _, ok := _c.mutation.BlogPostID(); !ok {
		return &ValidationError{Name: "blog_post_id", err: errors.New(`ent: missing required field "BlogPreviewToken.blog_post_id"`)}
	}
	if v, ok := _c.mutation.BlogPostID(); ok {
		if err := blogpreviewtoken.BlogPostIDValidator(v); err != nil {
			return &ValidationError{Name: "blog_post_id", err: fmt.Errorf(`ent: validator failed for field "BlogPreviewToken.blog_post_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "BlogPreviewToken.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := blogpreviewtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "BlogPreviewToken.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "BlogPreviewToken.language"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "BlogPreviewToken.expires_at"`)}
	}
	if len(_c.mutation.BlogPostIDs()) == 0 {
		return &ValidationError{Name: "blog_post", err: errors.New(`ent: missing required edge "BlogPreviewToken.blog_post"`)}
	}
	return nil
}

func (_c *BlogPreviewTokenCreate) sqlSave(ctx context.Context) (*BlogPreviewToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BlogPreviewToken.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BlogPreviewTokenCreate) createSpec() (*BlogPreviewToken, *sqlgraph.CreateSpec) {
	var (
		_node = &BlogPreviewToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(blogpreviewtoken.Table, sqlgraph.NewFieldSpec(blogpreviewtoken.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(blogpreviewtoken.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(blogpreviewtoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(blogpreviewtoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(blogpreviewtoken.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(blogpreviewtoken.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(blogpreviewtoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.BlogPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogpreviewtoken.BlogPostTable,
			Columns: []string{blogpreviewtoken.BlogPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BlogPostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BlogPreviewTokenCreateBulk is the builder for creating many BlogPreviewToken entities in bulk.
type BlogPreviewTokenCreateBulk struct {
	config
	err      error
	builders []*BlogPreviewTokenCreate
}

// Save creates the BlogPreviewToken entities in the database.
func (_c *BlogPreviewTokenCreateBulk) Save(ctx context.Context) ([]*BlogPreviewToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BlogPreviewToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlogPreviewTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BlogPreviewTokenCreateBulk) SaveX(ctx context.Context) []*BlogPreviewToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogPreviewTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogPreviewTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
