// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/night/go-astro-template/apps/api/ent/creditledger"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
)

// CreditLedgerDelete is the builder for deleting a CreditLedger entity.
type CreditLedgerDelete struct {
	config
	hooks    []Hook
	mutation *CreditLedgerMutation
}

// Where appends a list predicates to the CreditLedgerDelete builder.
func (_d *CreditLedgerDelete) Where(ps ...predicate.CreditLedger) *CreditLedgerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CreditLedgerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CreditLedgerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CreditLedgerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(creditledger.Table, sqlgraph.NewFieldSpec(creditledger.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CreditLedgerDeleteOne is the builder for deleting a single CreditLedger entity.
type CreditLedgerDeleteOne struct {
	_d *CreditLedgerDelete
}

// Where appends a list predicates to the CreditLedgerDelete builder.
func (_d *CreditLedgerDeleteOne) Where(ps ...predicate.CreditLedger) *CreditLedgerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CreditLedgerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{creditledger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CreditLedgerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
