// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/night/go-astro-template/apps/api/ent/file"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
	"github.com/night/go-astro-template/apps/api/ent/user"
)

// FileUpdate is the builder for updating File entities.
type FileUpdate struct {
	config
	hooks    []Hook
	mutation *FileMutation
}

// Where appends a list predicates to the FileUpdate builder.
func (_u *FileUpdate) Where(ps ...predicate.File) *FileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FileUpdate) SetUpdatedAt(v time.Time) *FileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *FileUpdate) SetObjectKey(v string) *FileUpdate {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *FileUpdate) SetNillableObjectKey(v *string) *FileUpdate {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *FileUpdate) SetFileName(v string) *FileUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *FileUpdate) SetNillableFileName(v *string) *FileUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *FileUpdate) SetContentType(v string) *FileUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *FileUpdate) SetNillableContentType(v *string) *FileUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *FileUpdate) SetSizeBytes(v int64) *FileUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *FileUpdate) SetNillableSizeBytes(v *int64) *FileUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *FileUpdate) AddSizeBytes(v int64) *FileUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetUploadedBy sets the "uploaded_by" field.
func (_u *FileUpdate) SetUploadedBy(v string) *FileUpdate {
	_u.mutation.SetUploadedBy(v)
	return _u
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_u *FileUpdate) SetNillableUploadedBy(v *string) *FileUpdate {
	if v != nil {
		_u.SetUploadedBy(*v)
	}
	return _u
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (_u *FileUpdate) ClearUploadedBy() *FileUpdate {
	_u.mutation.ClearUploadedBy()
	return _u
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (_u *FileUpdate) SetUploaderID(id string) *FileUpdate {
	_u.mutation.SetUploaderID(id)
	return _u
}

// SetNillableUploaderID sets the "uploader" edge to the User entity by ID if the given value is not nil.
func (_u *FileUpdate) SetNillableUploaderID(id *string) *FileUpdate {
	if id != nil {
		_u = _u.SetUploaderID(*id)
	}
	return _u
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *FileUpdate) SetUploader(v *User) *FileUpdate {
	return _u.SetUploaderID(v.ID)
}

// Mutation returns the FileMutation object of the builder.
func (_u *FileUpdate) Mutation() *FileMutation {
	return _u.mutation
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *FileUpdate) ClearUploader() *FileUpdate {
	_u.mutation.ClearUploader()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := file.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileUpdate) check() error {
	if v, ok := _u.mutation.ObjectKey(); ok {
		if err := file.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "File.object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := file.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "File.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := file.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "File.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := file.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "File.size_bytes": %w`, err)}
		}
	}
	return nil
}

func (_u *FileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(file.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(file.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(file.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(file.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(file.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(file.FieldSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.UploaderTable,
			Columns: []string{file.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.UploaderTable,
			Columns: []string{file.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FileUpdateOne is the builder for updating a single File entity.
type FileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FileUpdateOne) SetUpdatedAt(v time.Time) *FileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *FileUpdateOne) SetObjectKey(v string) *FileUpdateOne {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableObjectKey(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *FileUpdateOne) SetFileName(v string) *FileUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableFileName(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *FileUpdateOne) SetContentType(v string) *FileUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableContentType(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *FileUpdateOne) SetSizeBytes(v int64) *FileUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableSizeBytes(v *int64) *FileUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *FileUpdateOne) AddSizeBytes(v int64) *FileUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetUploadedBy sets the "uploaded_by" field.
func (_u *FileUpdateOne) SetUploadedBy(v string) *FileUpdateOne {
	_u.mutation.SetUploadedBy(v)
	return _u
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableUploadedBy(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetUploadedBy(*v)
	}
	return _u
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (_u *FileUpdateOne) ClearUploadedBy() *FileUpdateOne {
	_u.mutation.ClearUploadedBy()
	return _u
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (_u *FileUpdateOne) SetUploaderID(id string) *FileUpdateOne {
	_u.mutation.SetUploaderID(id)
	return _u
}

// SetNillableUploaderID sets the "uploader" edge to the User entity by ID if the given value is not nil.
func (_u *FileUpdateOne) SetNillableUploaderID(id *string) *FileUpdateOne {
	if id != nil {
		_u = _u.SetUploaderID(*id)
	}
	return _u
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *FileUpdateOne) SetUploader(v *User) *FileUpdateOne {
	return _u.SetUploaderID(v.ID)
}

// Mutation returns the FileMutation object of the builder.
func (_u *FileUpdateOne) Mutation() *FileMutation {
	return _u.mutation
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *FileUpdateOne) ClearUploader() *FileUpdateOne {
	_u.mutation.ClearUploader()
	return _u
}

// Where appends a list predicates to the FileUpdate builder.
func (_u *FileUpdateOne) Where(ps ...predicate.File) *FileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FileUpdateOne) Select(field string, fields ...string) *FileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated File entity.
func (_u *FileUpdateOne) Save(ctx context.Context) (*File, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUpdateOne) SaveX(ctx context.Context) *File {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := file.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileUpdateOne) check() error {
	if v, ok := _u.mutation.ObjectKey(); ok {
		if err := file.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "File.object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := file.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "File.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := file.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "File.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := file.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "File.size_bytes": %w`, err)}
		}
	}
	return nil
}

func (_u *FileUpdateOne) sqlSave(ctx context.Context) (_node *File, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "File.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, file.FieldID)
		for _, f := range fields {
			if !file.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != file.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(file.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(file.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(file.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(file.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(file.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(file.FieldSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.UploaderTable,
			Columns: []string{file.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.UploaderTable,
			Columns: []string{file.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &File{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
