// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/night/go-astro-template/apps/api/ent/idempotencykey"
)

// IdempotencyKey is the model entity for the IdempotencyKey schema.
type IdempotencyKey struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// ResponseStatus holds the value of the "response_status" field.
	ResponseStatus int `json:"response_status,omitempty"`
	// ResponsePayload holds the value of the "response_payload" field.
	ResponsePayload map[string]interface{} `json:"response_payload,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Consumed holds the value of the "consumed" field.
	Consumed     bool `json:"consumed,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IdempotencyKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case idempotencykey.FieldResponsePayload:
			values[i] = new([]byte)
		case idempotencykey.FieldConsumed:
			values[i] = new(sql.NullBool)
		case idempotencykey.FieldResponseStatus:
			values[i] = new(sql.NullInt64)
		case idempotencykey.FieldID, idempotencykey.FieldTenantID, idempotencykey.FieldScope, idempotencykey.FieldKey, idempotencykey.FieldRequestHash:
			values[i] = new(sql.NullString)
		case idempotencykey.FieldCreatedAt, idempotencykey.FieldUpdatedAt, idempotencykey.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IdempotencyKey fields.
func (_m *IdempotencyKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case idempotencykey.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case idempotencykey.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case idempotencykey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case idempotencykey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case idempotencykey.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case idempotencykey.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case idempotencykey.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = value.String
			}
		case idempotencykey.FieldResponseStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_status", values[i])
			} else if value.Valid {
				_m.ResponseStatus = int(value.Int64)
			}
		case idempotencykey.FieldResponsePayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponsePayload); err != nil {
					return fmt.Errorf("unmarshal field response_payload: %w", err)
				}
			}
		case idempotencykey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case idempotencykey.FieldConsumed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field consumed", values[i])
			} else if value.Valid {
				_m.Consumed = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IdempotencyKey.
// This includes values selected through modifiers, order, etc.
func (_m *IdempotencyKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IdempotencyKey.
// Note that you need to call IdempotencyKey.Unwrap() before calling this method if this IdempotencyKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IdempotencyKey) Update() *IdempotencyKeyUpdateOne {
	return NewIdempotencyKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IdempotencyKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IdempotencyKey) Unwrap() *IdempotencyKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IdempotencyKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IdempotencyKey) String() string {
	var builder strings.Builder
	builder.WriteString("IdempotencyKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(_m.RequestHash)
	builder.WriteString(", ")
	builder.WriteString("response_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseStatus))
	builder.WriteString(", ")
	builder.WriteString("response_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponsePayload))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("consumed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Consumed))
	builder.WriteByte(')')
	return builder.String()
}

// IdempotencyKeys is a parsable slice of IdempotencyKey.
type IdempotencyKeys []*IdempotencyKey
