// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/night/go-astro-template/apps/api/ent/maillog"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
)

// MailLogUpdate is the builder for updating MailLog entities.
type MailLogUpdate struct {
	config
	hooks    []Hook
	mutation *MailLogMutation
}

// Where appends a list predicates to the MailLogUpdate builder.
func (_u *MailLogUpdate) Where(ps ...predicate.MailLog) *MailLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MailLogUpdate) SetUpdatedAt(v time.Time) *MailLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTemplateKey sets the "template_key" field.
func (_u *MailLogUpdate) SetTemplateKey(v string) *MailLogUpdate {
	_u.mutation.SetTemplateKey(v)
	return _u
}

// SetNillableTemplateKey sets the "template_key" field if the given value is not nil.
func (_u *MailLogUpdate) SetNillableTemplateKey(v *string) *MailLogUpdate {
	if v != nil {
		_u.SetTemplateKey(*v)
	}
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *MailLogUpdate) SetRecipient(v string) *MailLogUpdate {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *MailLogUpdate) SetNillableRecipient(v *string) *MailLogUpdate {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *MailLogUpdate) SetSubject(v string) *MailLogUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *MailLogUpdate) SetNillableSubject(v *string) *MailLogUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MailLogUpdate) SetStatus(v string) *MailLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MailLogUpdate) SetNillableStatus(v *string) *MailLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *MailLogUpdate) SetErrorMessage(v string) *MailLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *MailLogUpdate) SetNillableErrorMessage(v *string) *MailLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *MailLogUpdate) SetSentAt(v time.Time) *MailLogUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *MailLogUpdate) SetNillableSentAt(v *time.Time) *MailLogUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *MailLogUpdate) ClearSentAt() *MailLogUpdate {
	_u.mutation.ClearSentAt()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *MailLogUpdate) SetPayload(v map[string]interface{}) *MailLogUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *MailLogUpdate) ClearPayload() *MailLogUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// Mutation returns the MailLogMutation object of the builder.
func (_u *MailLogUpdate) Mutation() *MailLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MailLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MailLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MailLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := maillog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MailLogUpdate) check() error {
	if v, ok := _u.mutation.Recipient(); ok {
		if err := maillog.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "MailLog.recipient": %w`, err)}
		}
	}
	return nil
}

func (_u *MailLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(maillog.Table, maillog.Columns, sqlgraph.NewFieldSpec(maillog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(maillog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TemplateKey(); ok {
		_spec.SetField(maillog.FieldTemplateKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(maillog.FieldRecipient, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(maillog.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(maillog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(maillog.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(maillog.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(maillog.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(maillog.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(maillog.FieldPayload, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{maillog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MailLogUpdateOne is the builder for updating a single MailLog entity.
type MailLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MailLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MailLogUpdateOne) SetUpdatedAt(v time.Time) *MailLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTemplateKey sets the "template_key" field.
func (_u *MailLogUpdateOne) SetTemplateKey(v string) *MailLogUpdateOne {
	_u.mutation.SetTemplateKey(v)
	return _u
}

// SetNillableTemplateKey sets the "template_key" field if the given value is not nil.
func (_u *MailLogUpdateOne) SetNillableTemplateKey(v *string) *MailLogUpdateOne {
	if v != nil {
		_u.SetTemplateKey(*v)
	}
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *MailLogUpdateOne) SetRecipient(v string) *MailLogUpdateOne {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *MailLogUpdateOne) SetNillableRecipient(v *string) *MailLogUpdateOne {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *MailLogUpdateOne) SetSubject(v string) *MailLogUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *MailLogUpdateOne) SetNillableSubject(v *string) *MailLogUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MailLogUpdateOne) SetStatus(v string) *MailLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MailLogUpdateOne) SetNillableStatus(v *string) *MailLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *MailLogUpdateOne) SetErrorMessage(v string) *MailLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *MailLogUpdateOne) SetNillableErrorMessage(v *string) *MailLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *MailLogUpdateOne) SetSentAt(v time.Time) *MailLogUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *MailLogUpdateOne) SetNillableSentAt(v *time.Time) *MailLogUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *MailLogUpdateOne) ClearSentAt() *MailLogUpdateOne {
	_u.mutation.ClearSentAt()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *MailLogUpdateOne) SetPayload(v map[string]interface{}) *MailLogUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *MailLogUpdateOne) ClearPayload() *MailLogUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// Mutation returns the MailLogMutation object of the builder.
func (_u *MailLogUpdateOne) Mutation() *MailLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the MailLogUpdate builder.
func (_u *MailLogUpdateOne) Where(ps ...predicate.MailLog) *MailLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MailLogUpdateOne) Select(field string, fields ...string) *MailLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MailLog entity.
func (_u *MailLogUpdateOne) Save(ctx context.Context) (*MailLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailLogUpdateOne) SaveX(ctx context.Context) *MailLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MailLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MailLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := maillog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MailLogUpdateOne) check() error {
	if v, ok := _u.mutation.Recipient(); ok {
		if err := maillog.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "MailLog.recipient": %w`, err)}
		}
	}
	return nil
}

func (_u *MailLogUpdateOne) sqlSave(ctx context.Context) (_node *MailLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(maillog.Table, maillog.Columns, sqlgraph.NewFieldSpec(maillog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MailLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, maillog.FieldID)
		for _, f := range fields {
			if !maillog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != maillog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(maillog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TemplateKey(); ok {
		_spec.SetField(maillog.FieldTemplateKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(maillog.FieldRecipient, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(maillog.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(maillog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(maillog.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(maillog.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(maillog.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(maillog.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(maillog.FieldPayload, field.TypeJSON)
	}
	_node = &MailLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{maillog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
