// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/night/go-astro-template/apps/api/ent/agentconversation"
	"github.com/night/go-astro-template/apps/api/ent/agentmessage"
	"github.com/night/go-astro-template/apps/api/ent/auditlog"
	"github.com/night/go-astro-template/apps/api/ent/billingtransaction"
	"github.com/night/go-astro-template/apps/api/ent/billingwebhookevent"
	"github.com/night/go-astro-template/apps/api/ent/blogpost"
	"github.com/night/go-astro-template/apps/api/ent/blogpreviewtoken"
	"github.com/night/go-astro-template/apps/api/ent/blogtranslation"
	"github.com/night/go-astro-template/apps/api/ent/creditaccount"
	"github.com/night/go-astro-template/apps/api/ent/creditledger"
	"github.com/night/go-astro-template/apps/api/ent/file"
	"github.com/night/go-astro-template/apps/api/ent/idempotencykey"
	"github.com/night/go-astro-template/apps/api/ent/jobrecord"
	"github.com/night/go-astro-template/apps/api/ent/maillog"
	"github.com/night/go-astro-template/apps/api/ent/marketplaceitem"
	"github.com/night/go-astro-template/apps/api/ent/marketplaceorder"
	"github.com/night/go-astro-template/apps/api/ent/passkeycredential"
	"github.com/night/go-astro-template/apps/api/ent/role"
	"github.com/night/go-astro-template/apps/api/ent/rolepermission"
	"github.com/night/go-astro-template/apps/api/ent/schema"
	"github.com/night/go-astro-template/apps/api/ent/session"
	"github.com/night/go-astro-template/apps/api/ent/systemsetting"
	"github.com/night/go-astro-template/apps/api/ent/team"
	"github.com/night/go-astro-template/apps/api/ent/teaminvite"
	"github.com/night/go-astro-template/apps/api/ent/teammembership"
	"github.com/night/go-astro-template/apps/api/ent/teamrole"
	"github.com/night/go-astro-template/apps/api/ent/user"
	"github.com/night/go-astro-template/apps/api/ent/userrolebinding"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentconversationMixin := schema.AgentConversation{}.Mixin()
	agentconversationMixinFields0 := agentconversationMixin[0].Fields()
	_ = agentconversationMixinFields0
	agentconversationMixinFields1 := agentconversationMixin[1].Fields()
	_ = agentconversationMixinFields1
	agentconversationMixinFields2 := agentconversationMixin[2].Fields()
	_ = agentconversationMixinFields2
	agentconversationFields := schema.AgentConversation{}.Fields()
	_ = agentconversationFields
	// agentconversationDescTenantID is the schema descriptor for tenant_id field.
	agentconversationDescTenantID := agentconversationMixinFields1[0].Descriptor()
	// agentconversation.DefaultTenantID holds the default value on creation for the tenant_id field.
	agentconversation.DefaultTenantID = agentconversationDescTenantID.Default.(string)
	// agentconversationDescCreatedAt is the schema descriptor for created_at field.
	agentconversationDescCreatedAt := agentconversationMixinFields2[0].Descriptor()
	// agentconversation.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentconversation.DefaultCreatedAt = agentconversationDescCreatedAt.Default.(func() time.Time)
	// agentconversationDescUpdatedAt is the schema descriptor for updated_at field.
	agentconversationDescUpdatedAt := agentconversationMixinFields2[1].Descriptor()
	// agentconversation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentconversation.DefaultUpdatedAt = agentconversationDescUpdatedAt.Default.(func() time.Time)
	// agentconversation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentconversation.UpdateDefaultUpdatedAt = agentconversationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentconversationDescUserID is the schema descriptor for user_id field.
	agentconversationDescUserID := agentconversationFields[0].Descriptor()
	// agentconversation.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	agentconversation.UserIDValidator = agentconversationDescUserID.Validators[0].(func(string) error)
	// agentconversationDescTitle is the schema descriptor for title field.
	agentconversationDescTitle := agentconversationFields[1].Descriptor()
	// agentconversation.DefaultTitle holds the default value on creation for the title field.
	agentconversation.DefaultTitle = agentconversationDescTitle.Default.(string)
	// agentconversationDescID is the schema descriptor for id field.
	agentconversationDescID := agentconversationMixinFields0[0].Descriptor()
	// agentconversation.DefaultID holds the default value on creation for the id field.
	agentconversation.DefaultID = agentconversationDescID.Default.(func() string)
	agentmessageMixin := schema.AgentMessage{}.Mixin()
	agentmessageMixinFields0 := agentmessageMixin[0].Fields()
	_ = agentmessageMixinFields0
	agentmessageMixinFields1 := agentmessageMixin[1].Fields()
	_ = agentmessageMixinFields1
	agentmessageMixinFields2 := agentmessageMixin[2].Fields()
	_ = agentmessageMixinFields2
	agentmessageFields := schema.AgentMessage{}.Fields()
	_ = agentmessageFields
	// agentmessageDescTenantID is the schema descriptor for tenant_id field.
	agentmessageDescTenantID := agentmessageMixinFields1[0].Descriptor()
	// agentmessage.DefaultTenantID holds the default value on creation for the tenant_id field.
	agentmessage.DefaultTenantID = agentmessageDescTenantID.Default.(string)
	// agentmessageDescCreatedAt is the schema descriptor for created_at field.
	agentmessageDescCreatedAt := agentmessageMixinFields2[0].Descriptor()
	// agentmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentmessage.DefaultCreatedAt = agentmessageDescCreatedAt.Default.(func() time.Time)
	// agentmessageDescUpdatedAt is the schema descriptor for updated_at field.
	agentmessageDescUpdatedAt := agentmessageMixinFields2[1].Descriptor()
	// agentmessage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentmessage.DefaultUpdatedAt = agentmessageDescUpdatedAt.Default.(func() time.Time)
	// agentmessage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentmessage.UpdateDefaultUpdatedAt = agentmessageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentmessageDescConversationID is the schema descriptor for conversation_id field.
	agentmessageDescConversationID := agentmessageFields[0].Descriptor()
	// agentmessage.ConversationIDValidator is a validator for the "conversation_id" field. It is called by the builders before save.
	agentmessage.ConversationIDValidator = agentmessageDescConversationID.Validators[0].(func(string) error)
	// agentmessageDescRole is the schema descriptor for role field.
	agentmessageDescRole := agentmessageFields[1].Descriptor()
	// agentmessage.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	agentmessage.RoleValidator = agentmessageDescRole.Validators[0].(func(string) error)
	// agentmessageDescContent is the schema descriptor for content field.
	agentmessageDescContent := agentmessageFields[2].Descriptor()
	// agentmessage.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	agentmessage.ContentValidator = agentmessageDescContent.Validators[0].(func(string) error)
	// agentmessageDescID is the schema descriptor for id field.
	agentmessageDescID := agentmessageMixinFields0[0].Descriptor()
	// agentmessage.DefaultID holds the default value on creation for the id field.
	agentmessage.DefaultID = agentmessageDescID.Default.(func() string)
	auditlogMixin := schema.AuditLog{}.Mixin()
	auditlogMixinFields0 := auditlogMixin[0].Fields()
	_ = auditlogMixinFields0
	auditlogMixinFields1 := auditlogMixin[1].Fields()
	_ = auditlogMixinFields1
	auditlogMixinFields2 := auditlogMixin[2].Fields()
	_ = auditlogMixinFields2
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescTenantID is the schema descriptor for tenant_id field.
	auditlogDescTenantID := auditlogMixinFields1[0].Descriptor()
	// auditlog.DefaultTenantID holds the default value on creation for the tenant_id field.
	auditlog.DefaultTenantID = auditlogDescTenantID.Default.(string)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogMixinFields2[0].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	// auditlogDescUpdatedAt is the schema descriptor for updated_at field.
	auditlogDescUpdatedAt := auditlogMixinFields2[1].Descriptor()
	// auditlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	auditlog.DefaultUpdatedAt = auditlogDescUpdatedAt.Default.(func() time.Time)
	// auditlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	auditlog.UpdateDefaultUpdatedAt = auditlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// auditlogDescActorEmail is the schema descriptor for actor_email field.
	auditlogDescActorEmail := auditlogFields[0].Descriptor()
	// auditlog.ActorEmailValidator is a validator for the "actor_email" field. It is called by the builders before save.
	auditlog.ActorEmailValidator = auditlogDescActorEmail.Validators[0].(func(string) error)
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[1].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescResource is the schema descriptor for resource field.
	auditlogDescResource := auditlogFields[2].Descriptor()
	// auditlog.ResourceValidator is a validator for the "resource" field. It is called by the builders before save.
	auditlog.ResourceValidator = auditlogDescResource.Validators[0].(func(string) error)
	// auditlogDescDetail is the schema descriptor for detail field.
	auditlogDescDetail := auditlogFields[3].Descriptor()
	// auditlog.DefaultDetail holds the default value on creation for the detail field.
	auditlog.DefaultDetail = auditlogDescDetail.Default.(string)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogMixinFields0[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() string)
	billingtransactionMixin := schema.BillingTransaction{}.Mixin()
	billingtransactionMixinFields0 := billingtransactionMixin[0].Fields()
	_ = billingtransactionMixinFields0
	billingtransactionMixinFields1 := billingtransactionMixin[1].Fields()
	_ = billingtransactionMixinFields1
	billingtransactionMixinFields2 := billingtransactionMixin[2].Fields()
	_ = billingtransactionMixinFields2
	billingtransactionFields := schema.BillingTransaction{}.Fields()
	_ = billingtransactionFields
	// billingtransactionDescTenantID is the schema descriptor for tenant_id field.
	billingtransactionDescTenantID := billingtransactionMixinFields1[0].Descriptor()
	// billingtransaction.DefaultTenantID holds the default value on creation for the tenant_id field.
	billingtransaction.DefaultTenantID = billingtransactionDescTenantID.Default.(string)
	// billingtransactionDescCreatedAt is the schema descriptor for created_at field.
	billingtransactionDescCreatedAt := billingtransactionMixinFields2[0].Descriptor()
	// billingtransaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	billingtransaction.DefaultCreatedAt = billingtransactionDescCreatedAt.Default.(func() time.Time)
	// billingtransactionDescUpdatedAt is the schema descriptor for updated_at field.
	billingtransactionDescUpdatedAt := billingtransactionMixinFields2[1].Descriptor()
	// billingtransaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	billingtransaction.DefaultUpdatedAt = billingtransactionDescUpdatedAt.Default.(func() time.Time)
	// billingtransaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	billingtransaction.UpdateDefaultUpdatedAt = billingtransactionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// billingtransactionDescUserID is the schema descriptor for user_id field.
	billingtransactionDescUserID := billingtransactionFields[0].Descriptor()
	// billingtransaction.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	billingtransaction.UserIDValidator = billingtransactionDescUserID.Validators[0].(func(string) error)
	// billingtransactionDescProvider is the schema descriptor for provider field.
	billingtransactionDescProvider := billingtransactionFields[1].Descriptor()
	// billingtransaction.DefaultProvider holds the default value on creation for the provider field.
	billingtransaction.DefaultProvider = billingtransactionDescProvider.Default.(string)
	// billingtransactionDescPaymentIntentID is the schema descriptor for payment_intent_id field.
	billingtransactionDescPaymentIntentID := billingtransactionFields[2].Descriptor()
	// billingtransaction.DefaultPaymentIntentID holds the default value on creation for the payment_intent_id field.
	billingtransaction.DefaultPaymentIntentID = billingtransactionDescPaymentIntentID.Default.(string)
	// billingtransactionDescAmount is the schema descriptor for amount field.
	billingtransactionDescAmount := billingtransactionFields[3].Descriptor()
	// billingtransaction.DefaultAmount holds the default value on creation for the amount field.
	billingtransaction.DefaultAmount = billingtransactionDescAmount.Default.(int64)
	// billingtransactionDescStatus is the schema descriptor for status field.
	billingtransactionDescStatus := billingtransactionFields[4].Descriptor()
	// billingtransaction.DefaultStatus holds the default value on creation for the status field.
	billingtransaction.DefaultStatus = billingtransactionDescStatus.Default.(string)
	// billingtransactionDescID is the schema descriptor for id field.
	billingtransactionDescID := billingtransactionMixinFields0[0].Descriptor()
	// billingtransaction.DefaultID holds the default value on creation for the id field.
	billingtransaction.DefaultID = billingtransactionDescID.Default.(func() string)
	billingwebhookeventMixin := schema.BillingWebhookEvent{}.Mixin()
	billingwebhookeventMixinFields0 := billingwebhookeventMixin[0].Fields()
	_ = billingwebhookeventMixinFields0
	billingwebhookeventMixinFields1 := billingwebhookeventMixin[1].Fields()
	_ = billingwebhookeventMixinFields1
	billingwebhookeventMixinFields2 := billingwebhookeventMixin[2].Fields()
	_ = billingwebhookeventMixinFields2
	billingwebhookeventFields := schema.BillingWebhookEvent{}.Fields()
	_ = billingwebhookeventFields
	// billingwebhookeventDescTenantID is the schema descriptor for tenant_id field.
	billingwebhookeventDescTenantID := billingwebhookeventMixinFields1[0].Descriptor()
	// billingwebhookevent.DefaultTenantID holds the default value on creation for the tenant_id field.
	billingwebhookevent.DefaultTenantID = billingwebhookeventDescTenantID.Default.(string)
	// billingwebhookeventDescCreatedAt is the schema descriptor for created_at field.
	billingwebhookeventDescCreatedAt := billingwebhookeventMixinFields2[0].Descriptor()
	// billingwebhookevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	billingwebhookevent.DefaultCreatedAt = billingwebhookeventDescCreatedAt.Default.(func() time.Time)
	// billingwebhookeventDescUpdatedAt is the schema descriptor for updated_at field.
	billingwebhookeventDescUpdatedAt := billingwebhookeventMixinFields2[1].Descriptor()
	// billingwebhookevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	billingwebhookevent.DefaultUpdatedAt = billingwebhookeventDescUpdatedAt.Default.(func() time.Time)
	// billingwebhookevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	billingwebhookevent.UpdateDefaultUpdatedAt = billingwebhookeventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// billingwebhookeventDescProvider is the schema descriptor for provider field.
	billingwebhookeventDescProvider := billingwebhookeventFields[0].Descriptor()
	// billingwebhookevent.DefaultProvider holds the default value on creation for the provider field.
	billingwebhookevent.DefaultProvider = billingwebhookeventDescProvider.Default.(string)
	// billingwebhookeventDescEventID is the schema descriptor for event_id field.
	billingwebhookeventDescEventID := billingwebhookeventFields[1].Descriptor()
	// billingwebhookevent.EventIDValidator is a validator for the "event_id" field. It is called by the builders before save.
	billingwebhookevent.EventIDValidator = billingwebhookeventDescEventID.Validators[0].(func(string) error)
	// billingwebhookeventDescProcessedAt is the schema descriptor for processed_at field.
	billingwebhookeventDescProcessedAt := billingwebhookeventFields[3].Descriptor()
	// billingwebhookevent.DefaultProcessedAt holds the default value on creation for the processed_at field.
	billingwebhookevent.DefaultProcessedAt = billingwebhookeventDescProcessedAt.Default.(func() time.Time)
	// billingwebhookeventDescID is the schema descriptor for id field.
	billingwebhookeventDescID := billingwebhookeventMixinFields0[0].Descriptor()
	// billingwebhookevent.DefaultID holds the default value on creation for the id field.
	billingwebhookevent.DefaultID = billingwebhookeventDescID.Default.(func() string)
	blogpostMixin := schema.BlogPost{}.Mixin()
	blogpostMixinFields0 := blogpostMixin[0].Fields()
	_ = blogpostMixinFields0
	blogpostMixinFields1 := blogpostMixin[1].Fields()
	_ = blogpostMixinFields1
	blogpostMixinFields2 := blogpostMixin[2].Fields()
	_ = blogpostMixinFields2
	blogpostFields := schema.BlogPost{}.Fields()
	_ = blogpostFields
	// blogpostDescTenantID is the schema descriptor for tenant_id field.
	blogpostDescTenantID := blogpostMixinFields1[0].Descriptor()
	// blogpost.DefaultTenantID holds the default value on creation for the tenant_id field.
	blogpost.DefaultTenantID = blogpostDescTenantID.Default.(string)
	// blogpostDescCreatedAt is the schema descriptor for created_at field.
	blogpostDescCreatedAt := blogpostMixinFields2[0].Descriptor()
	// blogpost.DefaultCreatedAt holds the default value on creation for the created_at field.
	blogpost.DefaultCreatedAt = blogpostDescCreatedAt.Default.(func() time.Time)
	// blogpostDescUpdatedAt is the schema descriptor for updated_at field.
	blogpostDescUpdatedAt := blogpostMixinFields2[1].Descriptor()
	// blogpost.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blogpost.DefaultUpdatedAt = blogpostDescUpdatedAt.Default.(func() time.Time)
	// blogpost.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	blogpost.UpdateDefaultUpdatedAt = blogpostDescUpdatedAt.UpdateDefault.(func() time.Time)
	// blogpostDescSlug is the schema descriptor for slug field.
	blogpostDescSlug := blogpostFields[0].Descriptor()
	// blogpost.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	blogpost.SlugValidator = blogpostDescSlug.Validators[0].(func(string) error)
	// blogpostDescStatus is the schema descriptor for status field.
	blogpostDescStatus := blogpostFields[1].Descriptor()
	// blogpost.DefaultStatus holds the default value on creation for the status field.
	blogpost.DefaultStatus = blogpostDescStatus.Default.(string)
	// blogpostDescDefaultLanguage is the schema descriptor for default_language field.
	blogpostDescDefaultLanguage := blogpostFields[2].Descriptor()
	// blogpost.DefaultDefaultLanguage holds the default value on creation for the default_language field.
	blogpost.DefaultDefaultLanguage = blogpostDescDefaultLanguage.Default.(string)
	// blogpostDescAuthorName is the schema descriptor for author_name field.
	blogpostDescAuthorName := blogpostFields[3].Descriptor()
	// blogpost.DefaultAuthorName holds the default value on creation for the author_name field.
	blogpost.DefaultAuthorName = blogpostDescAuthorName.Default.(string)
	// blogpostDescID is the schema descriptor for id field.
	blogpostDescID := blogpostMixinFields0[0].Descriptor()
	// blogpost.DefaultID holds the default value on creation for the id field.
	blogpost.DefaultID = blogpostDescID.Default.(func() string)
	blogpreviewtokenMixin := schema.BlogPreviewToken{}.Mixin()
	blogpreviewtokenMixinFields0 := blogpreviewtokenMixin[0].Fields()
	_ = blogpreviewtokenMixinFields0
	blogpreviewtokenMixinFields1 := blogpreviewtokenMixin[1].Fields()
	_ = blogpreviewtokenMixinFields1
	blogpreviewtokenMixinFields2 := blogpreviewtokenMixin[2].Fields()
	_ = blogpreviewtokenMixinFields2
	blogpreviewtokenFields := schema.BlogPreviewToken{}.Fields()
	_ = blogpreviewtokenFields
	// blogpreviewtokenDescTenantID is the schema descriptor for tenant_id field.
	blogpreviewtokenDescTenantID := blogpreviewtokenMixinFields1[0].Descriptor()
	// blogpreviewtoken.DefaultTenantID holds the default value on creation for the tenant_id field.
	blogpreviewtoken.DefaultTenantID = blogpreviewtokenDescTenantID.Default.(string)
	// blogpreviewtokenDescCreatedAt is the schema descriptor for created_at field.
	blogpreviewtokenDescCreatedAt := blogpreviewtokenMixinFields2[0].Descriptor()
	// blogpreviewtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	blogpreviewtoken.DefaultCreatedAt = blogpreviewtokenDescCreatedAt.Default.(func() time.Time)
	// blogpreviewtokenDescUpdatedAt is the schema descriptor for updated_at field.
	blogpreviewtokenDescUpdatedAt := blogpreviewtokenMixinFields2[1].Descriptor()
	// blogpreviewtoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blogpreviewtoken.DefaultUpdatedAt = blogpreviewtokenDescUpdatedAt.Default.(func() time.Time)
	// blogpreviewtoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	blogpreviewtoken.UpdateDefaultUpdatedAt = blogpreviewtokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// blogpreviewtokenDescBlogPostID is the schema descriptor for blog_post_id field.
	blogpreviewtokenDescBlogPostID := blogpreviewtokenFields[0].Descriptor()
	// blogpreviewtoken.BlogPostIDValidator is a validator for the "blog_post_id" field. It is called by the builders before save.
	blogpreviewtoken.BlogPostIDValidator = blogpreviewtokenDescBlogPostID.Validators[0].(func(string) error)
	// blogpreviewtokenDescToken is the schema descriptor for token field.
	blogpreviewtokenDescToken := blogpreviewtokenFields[1].Descriptor()
	// blogpreviewtoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	blogpreviewtoken.TokenValidator = blogpreviewtokenDescToken.Validators[0].(func(string) error)
	// blogpreviewtokenDescLanguage is the schema descriptor for language field.
	blogpreviewtokenDescLanguage := blogpreviewtokenFields[2].Descriptor()
	// blogpreviewtoken.DefaultLanguage holds the default value on creation for the language field.
	blogpreviewtoken.DefaultLanguage = blogpreviewtokenDescLanguage.Default.(string)
	// blogpreviewtokenDescExpiresAt is the schema descriptor for expires_at field.
	blogpreviewtokenDescExpiresAt := blogpreviewtokenFields[3].Descriptor()
	// blogpreviewtoken.DefaultExpiresAt holds the default value on creation for the expires_at field.
	blogpreviewtoken.DefaultExpiresAt = blogpreviewtokenDescExpiresAt.Default.(func() time.Time)
	// blogpreviewtokenDescID is the schema descriptor for id field.
	blogpreviewtokenDescID := blogpreviewtokenMixinFields0[0].Descriptor()
	// blogpreviewtoken.DefaultID holds the default value on creation for the id field.
	blogpreviewtoken.DefaultID = blogpreviewtokenDescID.Default.(func() string)
	blogtranslationMixin := schema.BlogTranslation{}.Mixin()
	blogtranslationMixinFields0 := blogtranslationMixin[0].Fields()
	_ = blogtranslationMixinFields0
	blogtranslationMixinFields1 := blogtranslationMixin[1].Fields()
	_ = blogtranslationMixinFields1
	blogtranslationMixinFields2 := blogtranslationMixin[2].Fields()
	_ = blogtranslationMixinFields2
	blogtranslationFields := schema.BlogTranslation{}.Fields()
	_ = blogtranslationFields
	// blogtranslationDescTenantID is the schema descriptor for tenant_id field.
	blogtranslationDescTenantID := blogtranslationMixinFields1[0].Descriptor()
	// blogtranslation.DefaultTenantID holds the default value on creation for the tenant_id field.
	blogtranslation.DefaultTenantID = blogtranslationDescTenantID.Default.(string)
	// blogtranslationDescCreatedAt is the schema descriptor for created_at field.
	blogtranslationDescCreatedAt := blogtranslationMixinFields2[0].Descriptor()
	// blogtranslation.DefaultCreatedAt holds the default value on creation for the created_at field.
	blogtranslation.DefaultCreatedAt = blogtranslationDescCreatedAt.Default.(func() time.Time)
	// blogtranslationDescUpdatedAt is the schema descriptor for updated_at field.
	blogtranslationDescUpdatedAt := blogtranslationMixinFields2[1].Descriptor()
	// blogtranslation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blogtranslation.DefaultUpdatedAt = blogtranslationDescUpdatedAt.Default.(func() time.Time)
	// blogtranslation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	blogtranslation.UpdateDefaultUpdatedAt = blogtranslationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// blogtranslationDescBlogPostID is the schema descriptor for blog_post_id field.
	blogtranslationDescBlogPostID := blogtranslationFields[0].Descriptor()
	// blogtranslation.BlogPostIDValidator is a validator for the "blog_post_id" field. It is called by the builders before save.
	blogtranslation.BlogPostIDValidator = blogtranslationDescBlogPostID.Validators[0].(func(string) error)
	// blogtranslationDescLanguage is the schema descriptor for language field.
	blogtranslationDescLanguage := blogtranslationFields[1].Descriptor()
	// blogtranslation.LanguageValidator is a validator for the "language" field. It is called by the builders before save.
	blogtranslation.LanguageValidator = blogtranslationDescLanguage.Validators[0].(func(string) error)
	// blogtranslationDescTitle is the schema descriptor for title field.
	blogtranslationDescTitle := blogtranslationFields[2].Descriptor()
	// blogtranslation.DefaultTitle holds the default value on creation for the title field.
	blogtranslation.DefaultTitle = blogtranslationDescTitle.Default.(string)
	// blogtranslationDescContent is the schema descriptor for content field.
	blogtranslationDescContent := blogtranslationFields[4].Descriptor()
	// blogtranslation.DefaultContent holds the default value on creation for the content field.
	blogtranslation.DefaultContent = blogtranslationDescContent.Default.(string)
	// blogtranslationDescID is the schema descriptor for id field.
	blogtranslationDescID := blogtranslationMixinFields0[0].Descriptor()
	// blogtranslation.DefaultID holds the default value on creation for the id field.
	blogtranslation.DefaultID = blogtranslationDescID.Default.(func() string)
	creditaccountMixin := schema.CreditAccount{}.Mixin()
	creditaccountMixinFields0 := creditaccountMixin[0].Fields()
	_ = creditaccountMixinFields0
	creditaccountMixinFields1 := creditaccountMixin[1].Fields()
	_ = creditaccountMixinFields1
	creditaccountMixinFields2 := creditaccountMixin[2].Fields()
	_ = creditaccountMixinFields2
	creditaccountFields := schema.CreditAccount{}.Fields()
	_ = creditaccountFields
	// creditaccountDescTenantID is the schema descriptor for tenant_id field.
	creditaccountDescTenantID := creditaccountMixinFields1[0].Descriptor()
	// creditaccount.DefaultTenantID holds the default value on creation for the tenant_id field.
	creditaccount.DefaultTenantID = creditaccountDescTenantID.Default.(string)
	// creditaccountDescCreatedAt is the schema descriptor for created_at field.
	creditaccountDescCreatedAt := creditaccountMixinFields2[0].Descriptor()
	// creditaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	creditaccount.DefaultCreatedAt = creditaccountDescCreatedAt.Default.(func() time.Time)
	// creditaccountDescUpdatedAt is the schema descriptor for updated_at field.
	creditaccountDescUpdatedAt := creditaccountMixinFields2[1].Descriptor()
	// creditaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	creditaccount.DefaultUpdatedAt = creditaccountDescUpdatedAt.Default.(func() time.Time)
	// creditaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	creditaccount.UpdateDefaultUpdatedAt = creditaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// creditaccountDescUserID is the schema descriptor for user_id field.
	creditaccountDescUserID := creditaccountFields[0].Descriptor()
	// creditaccount.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	creditaccount.UserIDValidator = creditaccountDescUserID.Validators[0].(func(string) error)
	// creditaccountDescBalance is the schema descriptor for balance field.
	creditaccountDescBalance := creditaccountFields[1].Descriptor()
	// creditaccount.DefaultBalance holds the default value on creation for the balance field.
	creditaccount.DefaultBalance = creditaccountDescBalance.Default.(int64)
	// creditaccountDescVersion is the schema descriptor for version field.
	creditaccountDescVersion := creditaccountFields[2].Descriptor()
	// creditaccount.DefaultVersion holds the default value on creation for the version field.
	creditaccount.DefaultVersion = creditaccountDescVersion.Default.(int)
	// creditaccountDescID is the schema descriptor for id field.
	creditaccountDescID := creditaccountMixinFields0[0].Descriptor()
	// creditaccount.DefaultID holds the default value on creation for the id field.
	creditaccount.DefaultID = creditaccountDescID.Default.(func() string)
	creditledgerMixin := schema.CreditLedger{}.Mixin()
	creditledgerMixinFields0 := creditledgerMixin[0].Fields()
	_ = creditledgerMixinFields0
	creditledgerMixinFields1 := creditledgerMixin[1].Fields()
	_ = creditledgerMixinFields1
	creditledgerMixinFields2 := creditledgerMixin[2].Fields()
	_ = creditledgerMixinFields2
	creditledgerFields := schema.CreditLedger{}.Fields()
	_ = creditledgerFields
	// creditledgerDescTenantID is the schema descriptor for tenant_id field.
	creditledgerDescTenantID := creditledgerMixinFields1[0].Descriptor()
	// creditledger.DefaultTenantID holds the default value on creation for the tenant_id field.
	creditledger.DefaultTenantID = creditledgerDescTenantID.Default.(string)
	// creditledgerDescCreatedAt is the schema descriptor for created_at field.
	creditledgerDescCreatedAt := creditledgerMixinFields2[0].Descriptor()
	// creditledger.DefaultCreatedAt holds the default value on creation for the created_at field.
	creditledger.DefaultCreatedAt = creditledgerDescCreatedAt.Default.(func() time.Time)
	// creditledgerDescUpdatedAt is the schema descriptor for updated_at field.
	creditledgerDescUpdatedAt := creditledgerMixinFields2[1].Descriptor()
	// creditledger.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	creditledger.DefaultUpdatedAt = creditledgerDescUpdatedAt.Default.(func() time.Time)
	// creditledger.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	creditledger.UpdateDefaultUpdatedAt = creditledgerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// creditledgerDescUserID is the schema descriptor for user_id field.
	creditledgerDescUserID := creditledgerFields[0].Descriptor()
	// creditledger.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	creditledger.UserIDValidator = creditledgerDescUserID.Validators[0].(func(string) error)
	// creditledgerDescDelta is the schema descriptor for delta field.
	creditledgerDescDelta := creditledgerFields[1].Descriptor()
	// creditledger.DefaultDelta holds the default value on creation for the delta field.
	creditledger.DefaultDelta = creditledgerDescDelta.Default.(int64)
	// creditledgerDescReason is the schema descriptor for reason field.
	creditledgerDescReason := creditledgerFields[2].Descriptor()
	// creditledger.DefaultReason holds the default value on creation for the reason field.
	creditledger.DefaultReason = creditledgerDescReason.Default.(string)
	// creditledgerDescRefType is the schema descriptor for ref_type field.
	creditledgerDescRefType := creditledgerFields[3].Descriptor()
	// creditledger.DefaultRefType holds the default value on creation for the ref_type field.
	creditledger.DefaultRefType = creditledgerDescRefType.Default.(string)
	// creditledgerDescRefID is the schema descriptor for ref_id field.
	creditledgerDescRefID := creditledgerFields[4].Descriptor()
	// creditledger.DefaultRefID holds the default value on creation for the ref_id field.
	creditledger.DefaultRefID = creditledgerDescRefID.Default.(string)
	// creditledgerDescID is the schema descriptor for id field.
	creditledgerDescID := creditledgerMixinFields0[0].Descriptor()
	// creditledger.DefaultID holds the default value on creation for the id field.
	creditledger.DefaultID = creditledgerDescID.Default.(func() string)
	fileMixin := schema.File{}.Mixin()
	fileMixinFields0 := fileMixin[0].Fields()
	_ = fileMixinFields0
	fileMixinFields1 := fileMixin[1].Fields()
	_ = fileMixinFields1
	fileMixinFields2 := fileMixin[2].Fields()
	_ = fileMixinFields2
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescTenantID is the schema descriptor for tenant_id field.
	fileDescTenantID := fileMixinFields1[0].Descriptor()
	// file.DefaultTenantID holds the default value on creation for the tenant_id field.
	file.DefaultTenantID = fileDescTenantID.Default.(string)
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileMixinFields2[0].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
	// fileDescUpdatedAt is the schema descriptor for updated_at field.
	fileDescUpdatedAt := fileMixinFields2[1].Descriptor()
	// file.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	file.DefaultUpdatedAt = fileDescUpdatedAt.Default.(func() time.Time)
	// file.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	file.UpdateDefaultUpdatedAt = fileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// fileDescObjectKey is the schema descriptor for object_key field.
	fileDescObjectKey := fileFields[0].Descriptor()
	// file.ObjectKeyValidator is a validator for the "object_key" field. It is called by the builders before save.
	file.ObjectKeyValidator = fileDescObjectKey.Validators[0].(func(string) error)
	// fileDescFileName is the schema descriptor for file_name field.
	fileDescFileName := fileFields[1].Descriptor()
	// file.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	file.FileNameValidator = fileDescFileName.Validators[0].(func(string) error)
	// fileDescContentType is the schema descriptor for content_type field.
	fileDescContentType := fileFields[2].Descriptor()
	// file.ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	file.ContentTypeValidator = fileDescContentType.Validators[0].(func(string) error)
	// fileDescSizeBytes is the schema descriptor for size_bytes field.
	fileDescSizeBytes := fileFields[3].Descriptor()
	// file.SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	file.SizeBytesValidator = fileDescSizeBytes.Validators[0].(func(int64) error)
	// fileDescID is the schema descriptor for id field.
	fileDescID := fileMixinFields0[0].Descriptor()
	// file.DefaultID holds the default value on creation for the id field.
	file.DefaultID = fileDescID.Default.(func() string)
	idempotencykeyMixin := schema.IdempotencyKey{}.Mixin()
	idempotencykeyMixinFields0 := idempotencykeyMixin[0].Fields()
	_ = idempotencykeyMixinFields0
	idempotencykeyMixinFields1 := idempotencykeyMixin[1].Fields()
	_ = idempotencykeyMixinFields1
	idempotencykeyMixinFields2 := idempotencykeyMixin[2].Fields()
	_ = idempotencykeyMixinFields2
	idempotencykeyFields := schema.IdempotencyKey{}.Fields()
	_ = idempotencykeyFields
	// idempotencykeyDescTenantID is the schema descriptor for tenant_id field.
	idempotencykeyDescTenantID := idempotencykeyMixinFields1[0].Descriptor()
	// idempotencykey.DefaultTenantID holds the default value on creation for the tenant_id field.
	idempotencykey.DefaultTenantID = idempotencykeyDescTenantID.Default.(string)
	// idempotencykeyDescCreatedAt is the schema descriptor for created_at field.
	idempotencykeyDescCreatedAt := idempotencykeyMixinFields2[0].Descriptor()
	// idempotencykey.DefaultCreatedAt holds the default value on creation for the created_at field.
	idempotencykey.DefaultCreatedAt = idempotencykeyDescCreatedAt.Default.(func() time.Time)
	// idempotencykeyDescUpdatedAt is the schema descriptor for updated_at field.
	idempotencykeyDescUpdatedAt := idempotencykeyMixinFields2[1].Descriptor()
	// idempotencykey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	idempotencykey.DefaultUpdatedAt = idempotencykeyDescUpdatedAt.Default.(func() time.Time)
	// idempotencykey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	idempotencykey.UpdateDefaultUpdatedAt = idempotencykeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// idempotencykeyDescScope is the schema descriptor for scope field.
	idempotencykeyDescScope := idempotencykeyFields[0].Descriptor()
	// idempotencykey.DefaultScope holds the default value on creation for the scope field.
	idempotencykey.DefaultScope = idempotencykeyDescScope.Default.(string)
	// idempotencykeyDescKey is the schema descriptor for key field.
	idempotencykeyDescKey := idempotencykeyFields[1].Descriptor()
	// idempotencykey.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	idempotencykey.KeyValidator = idempotencykeyDescKey.Validators[0].(func(string) error)
	// idempotencykeyDescRequestHash is the schema descriptor for request_hash field.
	idempotencykeyDescRequestHash := idempotencykeyFields[2].Descriptor()
	// idempotencykey.DefaultRequestHash holds the default value on creation for the request_hash field.
	idempotencykey.DefaultRequestHash = idempotencykeyDescRequestHash.Default.(string)
	// idempotencykeyDescResponseStatus is the schema descriptor for response_status field.
	idempotencykeyDescResponseStatus := idempotencykeyFields[3].Descriptor()
	// idempotencykey.DefaultResponseStatus holds the default value on creation for the response_status field.
	idempotencykey.DefaultResponseStatus = idempotencykeyDescResponseStatus.Default.(int)
	// idempotencykeyDescExpiresAt is the schema descriptor for expires_at field.
	idempotencykeyDescExpiresAt := idempotencykeyFields[5].Descriptor()
	// idempotencykey.DefaultExpiresAt holds the default value on creation for the expires_at field.
	idempotencykey.DefaultExpiresAt = idempotencykeyDescExpiresAt.Default.(func() time.Time)
	// idempotencykeyDescConsumed is the schema descriptor for consumed field.
	idempotencykeyDescConsumed := idempotencykeyFields[6].Descriptor()
	// idempotencykey.DefaultConsumed holds the default value on creation for the consumed field.
	idempotencykey.DefaultConsumed = idempotencykeyDescConsumed.Default.(bool)
	// idempotencykeyDescID is the schema descriptor for id field.
	idempotencykeyDescID := idempotencykeyMixinFields0[0].Descriptor()
	// idempotencykey.DefaultID holds the default value on creation for the id field.
	idempotencykey.DefaultID = idempotencykeyDescID.Default.(func() string)
	jobrecordMixin := schema.JobRecord{}.Mixin()
	jobrecordMixinFields0 := jobrecordMixin[0].Fields()
	_ = jobrecordMixinFields0
	jobrecordMixinFields1 := jobrecordMixin[1].Fields()
	_ = jobrecordMixinFields1
	jobrecordMixinFields2 := jobrecordMixin[2].Fields()
	_ = jobrecordMixinFields2
	jobrecordFields := schema.JobRecord{}.Fields()
	_ = jobrecordFields
	// jobrecordDescTenantID is the schema descriptor for tenant_id field.
	jobrecordDescTenantID := jobrecordMixinFields1[0].Descriptor()
	// jobrecord.DefaultTenantID holds the default value on creation for the tenant_id field.
	jobrecord.DefaultTenantID = jobrecordDescTenantID.Default.(string)
	// jobrecordDescCreatedAt is the schema descriptor for created_at field.
	jobrecordDescCreatedAt := jobrecordMixinFields2[0].Descriptor()
	// jobrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	jobrecord.DefaultCreatedAt = jobrecordDescCreatedAt.Default.(func() time.Time)
	// jobrecordDescUpdatedAt is the schema descriptor for updated_at field.
	jobrecordDescUpdatedAt := jobrecordMixinFields2[1].Descriptor()
	// jobrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	jobrecord.DefaultUpdatedAt = jobrecordDescUpdatedAt.Default.(func() time.Time)
	// jobrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	jobrecord.UpdateDefaultUpdatedAt = jobrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// jobrecordDescJobType is the schema descriptor for job_type field.
	jobrecordDescJobType := jobrecordFields[0].Descriptor()
	// jobrecord.JobTypeValidator is a validator for the "job_type" field. It is called by the builders before save.
	jobrecord.JobTypeValidator = jobrecordDescJobType.Validators[0].(func(string) error)
	// jobrecordDescStatus is the schema descriptor for status field.
	jobrecordDescStatus := jobrecordFields[1].Descriptor()
	// jobrecord.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	jobrecord.StatusValidator = jobrecordDescStatus.Validators[0].(func(string) error)
	// jobrecordDescQueue is the schema descriptor for queue field.
	jobrecordDescQueue := jobrecordFields[2].Descriptor()
	// jobrecord.DefaultQueue holds the default value on creation for the queue field.
	jobrecord.DefaultQueue = jobrecordDescQueue.Default.(string)
	// jobrecordDescAttempts is the schema descriptor for attempts field.
	jobrecordDescAttempts := jobrecordFields[3].Descriptor()
	// jobrecord.DefaultAttempts holds the default value on creation for the attempts field.
	jobrecord.DefaultAttempts = jobrecordDescAttempts.Default.(int)
	// jobrecord.AttemptsValidator is a validator for the "attempts" field. It is called by the builders before save.
	jobrecord.AttemptsValidator = jobrecordDescAttempts.Validators[0].(func(int) error)
	// jobrecordDescLastError is the schema descriptor for last_error field.
	jobrecordDescLastError := jobrecordFields[4].Descriptor()
	// jobrecord.DefaultLastError holds the default value on creation for the last_error field.
	jobrecord.DefaultLastError = jobrecordDescLastError.Default.(string)
	// jobrecordDescExecutedAt is the schema descriptor for executed_at field.
	jobrecordDescExecutedAt := jobrecordFields[5].Descriptor()
	// jobrecord.DefaultExecutedAt holds the default value on creation for the executed_at field.
	jobrecord.DefaultExecutedAt = jobrecordDescExecutedAt.Default.(func() time.Time)
	// jobrecordDescID is the schema descriptor for id field.
	jobrecordDescID := jobrecordMixinFields0[0].Descriptor()
	// jobrecord.DefaultID holds the default value on creation for the id field.
	jobrecord.DefaultID = jobrecordDescID.Default.(func() string)
	maillogMixin := schema.MailLog{}.Mixin()
	maillogMixinFields0 := maillogMixin[0].Fields()
	_ = maillogMixinFields0
	maillogMixinFields1 := maillogMixin[1].Fields()
	_ = maillogMixinFields1
	maillogMixinFields2 := maillogMixin[2].Fields()
	_ = maillogMixinFields2
	maillogFields := schema.MailLog{}.Fields()
	_ = maillogFields
	// maillogDescTenantID is the schema descriptor for tenant_id field.
	maillogDescTenantID := maillogMixinFields1[0].Descriptor()
	// maillog.DefaultTenantID holds the default value on creation for the tenant_id field.
	maillog.DefaultTenantID = maillogDescTenantID.Default.(string)
	// maillogDescCreatedAt is the schema descriptor for created_at field.
	maillogDescCreatedAt := maillogMixinFields2[0].Descriptor()
	// maillog.DefaultCreatedAt holds the default value on creation for the created_at field.
	maillog.DefaultCreatedAt = maillogDescCreatedAt.Default.(func() time.Time)
	// maillogDescUpdatedAt is the schema descriptor for updated_at field.
	maillogDescUpdatedAt := maillogMixinFields2[1].Descriptor()
	// maillog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	maillog.DefaultUpdatedAt = maillogDescUpdatedAt.Default.(func() time.Time)
	// maillog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	maillog.UpdateDefaultUpdatedAt = maillogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// maillogDescTemplateKey is the schema descriptor for template_key field.
	maillogDescTemplateKey := maillogFields[0].Descriptor()
	// maillog.DefaultTemplateKey holds the default value on creation for the template_key field.
	maillog.DefaultTemplateKey = maillogDescTemplateKey.Default.(string)
	// maillogDescRecipient is the schema descriptor for recipient field.
	maillogDescRecipient := maillogFields[1].Descriptor()
	// maillog.RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	maillog.RecipientValidator = maillogDescRecipient.Validators[0].(func(string) error)
	// maillogDescSubject is the schema descriptor for subject field.
	maillogDescSubject := maillogFields[2].Descriptor()
	// maillog.DefaultSubject holds the default value on creation for the subject field.
	maillog.DefaultSubject = maillogDescSubject.Default.(string)
	// maillogDescStatus is the schema descriptor for status field.
	maillogDescStatus := maillogFields[3].Descriptor()
	// maillog.DefaultStatus holds the default value on creation for the status field.
	maillog.DefaultStatus = maillogDescStatus.Default.(string)
	// maillogDescErrorMessage is the schema descriptor for error_message field.
	maillogDescErrorMessage := maillogFields[4].Descriptor()
	// maillog.DefaultErrorMessage holds the default value on creation for the error_message field.
	maillog.DefaultErrorMessage = maillogDescErrorMessage.Default.(string)
	// maillogDescID is the schema descriptor for id field.
	maillogDescID := maillogMixinFields0[0].Descriptor()
	// maillog.DefaultID holds the default value on creation for the id field.
	maillog.DefaultID = maillogDescID.Default.(func() string)
	marketplaceitemMixin := schema.MarketplaceItem{}.Mixin()
	marketplaceitemMixinFields0 := marketplaceitemMixin[0].Fields()
	_ = marketplaceitemMixinFields0
	marketplaceitemMixinFields1 := marketplaceitemMixin[1].Fields()
	_ = marketplaceitemMixinFields1
	marketplaceitemMixinFields2 := marketplaceitemMixin[2].Fields()
	_ = marketplaceitemMixinFields2
	marketplaceitemFields := schema.MarketplaceItem{}.Fields()
	_ = marketplaceitemFields
	// marketplaceitemDescTenantID is the schema descriptor for tenant_id field.
	marketplaceitemDescTenantID := marketplaceitemMixinFields1[0].Descriptor()
	// marketplaceitem.DefaultTenantID holds the default value on creation for the tenant_id field.
	marketplaceitem.DefaultTenantID = marketplaceitemDescTenantID.Default.(string)
	// marketplaceitemDescCreatedAt is the schema descriptor for created_at field.
	marketplaceitemDescCreatedAt := marketplaceitemMixinFields2[0].Descriptor()
	// marketplaceitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	marketplaceitem.DefaultCreatedAt = marketplaceitemDescCreatedAt.Default.(func() time.Time)
	// marketplaceitemDescUpdatedAt is the schema descriptor for updated_at field.
	marketplaceitemDescUpdatedAt := marketplaceitemMixinFields2[1].Descriptor()
	// marketplaceitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	marketplaceitem.DefaultUpdatedAt = marketplaceitemDescUpdatedAt.Default.(func() time.Time)
	// marketplaceitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	marketplaceitem.UpdateDefaultUpdatedAt = marketplaceitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// marketplaceitemDescCode is the schema descriptor for code field.
	marketplaceitemDescCode := marketplaceitemFields[0].Descriptor()
	// marketplaceitem.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	marketplaceitem.CodeValidator = marketplaceitemDescCode.Validators[0].(func(string) error)
	// marketplaceitemDescName is the schema descriptor for name field.
	marketplaceitemDescName := marketplaceitemFields[1].Descriptor()
	// marketplaceitem.NameValidator is a validator for the "name" field. It is called by the builders before save.
	marketplaceitem.NameValidator = marketplaceitemDescName.Validators[0].(func(string) error)
	// marketplaceitemDescItemType is the schema descriptor for item_type field.
	marketplaceitemDescItemType := marketplaceitemFields[2].Descriptor()
	// marketplaceitem.DefaultItemType holds the default value on creation for the item_type field.
	marketplaceitem.DefaultItemType = marketplaceitemDescItemType.Default.(string)
	// marketplaceitemDescPriceCredits is the schema descriptor for price_credits field.
	marketplaceitemDescPriceCredits := marketplaceitemFields[3].Descriptor()
	// marketplaceitem.DefaultPriceCredits holds the default value on creation for the price_credits field.
	marketplaceitem.DefaultPriceCredits = marketplaceitemDescPriceCredits.Default.(int64)
	// marketplaceitemDescEnabled is the schema descriptor for enabled field.
	marketplaceitemDescEnabled := marketplaceitemFields[4].Descriptor()
	// marketplaceitem.DefaultEnabled holds the default value on creation for the enabled field.
	marketplaceitem.DefaultEnabled = marketplaceitemDescEnabled.Default.(bool)
	// marketplaceitemDescID is the schema descriptor for id field.
	marketplaceitemDescID := marketplaceitemMixinFields0[0].Descriptor()
	// marketplaceitem.DefaultID holds the default value on creation for the id field.
	marketplaceitem.DefaultID = marketplaceitemDescID.Default.(func() string)
	marketplaceorderMixin := schema.MarketplaceOrder{}.Mixin()
	marketplaceorderMixinFields0 := marketplaceorderMixin[0].Fields()
	_ = marketplaceorderMixinFields0
	marketplaceorderMixinFields1 := marketplaceorderMixin[1].Fields()
	_ = marketplaceorderMixinFields1
	marketplaceorderMixinFields2 := marketplaceorderMixin[2].Fields()
	_ = marketplaceorderMixinFields2
	marketplaceorderFields := schema.MarketplaceOrder{}.Fields()
	_ = marketplaceorderFields
	// marketplaceorderDescTenantID is the schema descriptor for tenant_id field.
	marketplaceorderDescTenantID := marketplaceorderMixinFields1[0].Descriptor()
	// marketplaceorder.DefaultTenantID holds the default value on creation for the tenant_id field.
	marketplaceorder.DefaultTenantID = marketplaceorderDescTenantID.Default.(string)
	// marketplaceorderDescCreatedAt is the schema descriptor for created_at field.
	marketplaceorderDescCreatedAt := marketplaceorderMixinFields2[0].Descriptor()
	// marketplaceorder.DefaultCreatedAt holds the default value on creation for the created_at field.
	marketplaceorder.DefaultCreatedAt = marketplaceorderDescCreatedAt.Default.(func() time.Time)
	// marketplaceorderDescUpdatedAt is the schema descriptor for updated_at field.
	marketplaceorderDescUpdatedAt := marketplaceorderMixinFields2[1].Descriptor()
	// marketplaceorder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	marketplaceorder.DefaultUpdatedAt = marketplaceorderDescUpdatedAt.Default.(func() time.Time)
	// marketplaceorder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	marketplaceorder.UpdateDefaultUpdatedAt = marketplaceorderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// marketplaceorderDescUserID is the schema descriptor for user_id field.
	marketplaceorderDescUserID := marketplaceorderFields[0].Descriptor()
	// marketplaceorder.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	marketplaceorder.UserIDValidator = marketplaceorderDescUserID.Validators[0].(func(string) error)
	// marketplaceorderDescItemID is the schema descriptor for item_id field.
	marketplaceorderDescItemID := marketplaceorderFields[1].Descriptor()
	// marketplaceorder.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	marketplaceorder.ItemIDValidator = marketplaceorderDescItemID.Validators[0].(func(string) error)
	// marketplaceorderDescStatus is the schema descriptor for status field.
	marketplaceorderDescStatus := marketplaceorderFields[2].Descriptor()
	// marketplaceorder.DefaultStatus holds the default value on creation for the status field.
	marketplaceorder.DefaultStatus = marketplaceorderDescStatus.Default.(string)
	// marketplaceorderDescCostCredits is the schema descriptor for cost_credits field.
	marketplaceorderDescCostCredits := marketplaceorderFields[3].Descriptor()
	// marketplaceorder.DefaultCostCredits holds the default value on creation for the cost_credits field.
	marketplaceorder.DefaultCostCredits = marketplaceorderDescCostCredits.Default.(int64)
	// marketplaceorderDescID is the schema descriptor for id field.
	marketplaceorderDescID := marketplaceorderMixinFields0[0].Descriptor()
	// marketplaceorder.DefaultID holds the default value on creation for the id field.
	marketplaceorder.DefaultID = marketplaceorderDescID.Default.(func() string)
	passkeycredentialMixin := schema.PasskeyCredential{}.Mixin()
	passkeycredentialMixinFields0 := passkeycredentialMixin[0].Fields()
	_ = passkeycredentialMixinFields0
	passkeycredentialMixinFields1 := passkeycredentialMixin[1].Fields()
	_ = passkeycredentialMixinFields1
	passkeycredentialMixinFields2 := passkeycredentialMixin[2].Fields()
	_ = passkeycredentialMixinFields2
	passkeycredentialFields := schema.PasskeyCredential{}.Fields()
	_ = passkeycredentialFields
	// passkeycredentialDescTenantID is the schema descriptor for tenant_id field.
	passkeycredentialDescTenantID := passkeycredentialMixinFields1[0].Descriptor()
	// passkeycredential.DefaultTenantID holds the default value on creation for the tenant_id field.
	passkeycredential.DefaultTenantID = passkeycredentialDescTenantID.Default.(string)
	// passkeycredentialDescCreatedAt is the schema descriptor for created_at field.
	passkeycredentialDescCreatedAt := passkeycredentialMixinFields2[0].Descriptor()
	// passkeycredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	passkeycredential.DefaultCreatedAt = passkeycredentialDescCreatedAt.Default.(func() time.Time)
	// passkeycredentialDescUpdatedAt is the schema descriptor for updated_at field.
	passkeycredentialDescUpdatedAt := passkeycredentialMixinFields2[1].Descriptor()
	// passkeycredential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	passkeycredential.DefaultUpdatedAt = passkeycredentialDescUpdatedAt.Default.(func() time.Time)
	// passkeycredential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	passkeycredential.UpdateDefaultUpdatedAt = passkeycredentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	// passkeycredentialDescUserID is the schema descriptor for user_id field.
	passkeycredentialDescUserID := passkeycredentialFields[0].Descriptor()
	// passkeycredential.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	passkeycredential.UserIDValidator = passkeycredentialDescUserID.Validators[0].(func(string) error)
	// passkeycredentialDescCredentialID is the schema descriptor for credential_id field.
	passkeycredentialDescCredentialID := passkeycredentialFields[1].Descriptor()
	// passkeycredential.CredentialIDValidator is a validator for the "credential_id" field. It is called by the builders before save.
	passkeycredential.CredentialIDValidator = passkeycredentialDescCredentialID.Validators[0].(func(string) error)
	// passkeycredentialDescPublicKey is the schema descriptor for public_key field.
	passkeycredentialDescPublicKey := passkeycredentialFields[2].Descriptor()
	// passkeycredential.DefaultPublicKey holds the default value on creation for the public_key field.
	passkeycredential.DefaultPublicKey = passkeycredentialDescPublicKey.Default.(string)
	// passkeycredentialDescID is the schema descriptor for id field.
	passkeycredentialDescID := passkeycredentialMixinFields0[0].Descriptor()
	// passkeycredential.DefaultID holds the default value on creation for the id field.
	passkeycredential.DefaultID = passkeycredentialDescID.Default.(func() string)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleMixinFields2 := roleMixin[2].Fields()
	_ = roleMixinFields2
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescTenantID is the schema descriptor for tenant_id field.
	roleDescTenantID := roleMixinFields1[0].Descriptor()
	// role.DefaultTenantID holds the default value on creation for the tenant_id field.
	role.DefaultTenantID = roleDescTenantID.Default.(string)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields2[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields2[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescKey is the schema descriptor for key field.
	roleDescKey := roleFields[0].Descriptor()
	// role.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	role.KeyValidator = roleDescKey.Validators[0].(func(string) error)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[1].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[2].Descriptor()
	// role.DefaultDescription holds the default value on creation for the description field.
	role.DefaultDescription = roleDescDescription.Default.(string)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleMixinFields0[0].Descriptor()
	// role.DefaultID holds the default value on creation for the id field.
	role.DefaultID = roleDescID.Default.(func() string)
	rolepermissionMixin := schema.RolePermission{}.Mixin()
	rolepermissionMixinFields0 := rolepermissionMixin[0].Fields()
	_ = rolepermissionMixinFields0
	rolepermissionMixinFields1 := rolepermissionMixin[1].Fields()
	_ = rolepermissionMixinFields1
	rolepermissionMixinFields2 := rolepermissionMixin[2].Fields()
	_ = rolepermissionMixinFields2
	rolepermissionFields := schema.RolePermission{}.Fields()
	_ = rolepermissionFields
	// rolepermissionDescTenantID is the schema descriptor for tenant_id field.
	rolepermissionDescTenantID := rolepermissionMixinFields1[0].Descriptor()
	// rolepermission.DefaultTenantID holds the default value on creation for the tenant_id field.
	rolepermission.DefaultTenantID = rolepermissionDescTenantID.Default.(string)
	// rolepermissionDescCreatedAt is the schema descriptor for created_at field.
	rolepermissionDescCreatedAt := rolepermissionMixinFields2[0].Descriptor()
	// rolepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	rolepermission.DefaultCreatedAt = rolepermissionDescCreatedAt.Default.(func() time.Time)
	// rolepermissionDescUpdatedAt is the schema descriptor for updated_at field.
	rolepermissionDescUpdatedAt := rolepermissionMixinFields2[1].Descriptor()
	// rolepermission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rolepermission.DefaultUpdatedAt = rolepermissionDescUpdatedAt.Default.(func() time.Time)
	// rolepermission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rolepermission.UpdateDefaultUpdatedAt = rolepermissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rolepermissionDescRoleID is the schema descriptor for role_id field.
	rolepermissionDescRoleID := rolepermissionFields[0].Descriptor()
	// rolepermission.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	rolepermission.RoleIDValidator = rolepermissionDescRoleID.Validators[0].(func(string) error)
	// rolepermissionDescPermissionKey is the schema descriptor for permission_key field.
	rolepermissionDescPermissionKey := rolepermissionFields[1].Descriptor()
	// rolepermission.PermissionKeyValidator is a validator for the "permission_key" field. It is called by the builders before save.
	rolepermission.PermissionKeyValidator = rolepermissionDescPermissionKey.Validators[0].(func(string) error)
	// rolepermissionDescDescription is the schema descriptor for description field.
	rolepermissionDescDescription := rolepermissionFields[2].Descriptor()
	// rolepermission.DefaultDescription holds the default value on creation for the description field.
	rolepermission.DefaultDescription = rolepermissionDescDescription.Default.(string)
	// rolepermissionDescID is the schema descriptor for id field.
	rolepermissionDescID := rolepermissionMixinFields0[0].Descriptor()
	// rolepermission.DefaultID holds the default value on creation for the id field.
	rolepermission.DefaultID = rolepermissionDescID.Default.(func() string)
	sessionMixin := schema.Session{}.Mixin()
	sessionMixinFields0 := sessionMixin[0].Fields()
	_ = sessionMixinFields0
	sessionMixinFields1 := sessionMixin[1].Fields()
	_ = sessionMixinFields1
	sessionMixinFields2 := sessionMixin[2].Fields()
	_ = sessionMixinFields2
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescTenantID is the schema descriptor for tenant_id field.
	sessionDescTenantID := sessionMixinFields1[0].Descriptor()
	// session.DefaultTenantID holds the default value on creation for the tenant_id field.
	session.DefaultTenantID = sessionDescTenantID.Default.(string)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionMixinFields2[0].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionMixinFields2[1].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescUserID is the schema descriptor for user_id field.
	sessionDescUserID := sessionFields[0].Descriptor()
	// session.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	session.UserIDValidator = sessionDescUserID.Validators[0].(func(string) error)
	// sessionDescToken is the schema descriptor for token field.
	sessionDescToken := sessionFields[1].Descriptor()
	// session.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	session.TokenValidator = sessionDescToken.Validators[0].(func(string) error)
	// sessionDescExpiresAt is the schema descriptor for expires_at field.
	sessionDescExpiresAt := sessionFields[2].Descriptor()
	// session.DefaultExpiresAt holds the default value on creation for the expires_at field.
	session.DefaultExpiresAt = sessionDescExpiresAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionMixinFields0[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() string)
	systemsettingMixin := schema.SystemSetting{}.Mixin()
	systemsettingMixinFields0 := systemsettingMixin[0].Fields()
	_ = systemsettingMixinFields0
	systemsettingMixinFields1 := systemsettingMixin[1].Fields()
	_ = systemsettingMixinFields1
	systemsettingMixinFields2 := systemsettingMixin[2].Fields()
	_ = systemsettingMixinFields2
	systemsettingFields := schema.SystemSetting{}.Fields()
	_ = systemsettingFields
	// systemsettingDescTenantID is the schema descriptor for tenant_id field.
	systemsettingDescTenantID := systemsettingMixinFields1[0].Descriptor()
	// systemsetting.DefaultTenantID holds the default value on creation for the tenant_id field.
	systemsetting.DefaultTenantID = systemsettingDescTenantID.Default.(string)
	// systemsettingDescCreatedAt is the schema descriptor for created_at field.
	systemsettingDescCreatedAt := systemsettingMixinFields2[0].Descriptor()
	// systemsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemsetting.DefaultCreatedAt = systemsettingDescCreatedAt.Default.(func() time.Time)
	// systemsettingDescUpdatedAt is the schema descriptor for updated_at field.
	systemsettingDescUpdatedAt := systemsettingMixinFields2[1].Descriptor()
	// systemsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemsetting.DefaultUpdatedAt = systemsettingDescUpdatedAt.Default.(func() time.Time)
	// systemsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemsetting.UpdateDefaultUpdatedAt = systemsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// systemsettingDescCategory is the schema descriptor for category field.
	systemsettingDescCategory := systemsettingFields[0].Descriptor()
	// systemsetting.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	systemsetting.CategoryValidator = systemsettingDescCategory.Validators[0].(func(string) error)
	// systemsettingDescKey is the schema descriptor for key field.
	systemsettingDescKey := systemsettingFields[1].Descriptor()
	// systemsetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	systemsetting.KeyValidator = systemsettingDescKey.Validators[0].(func(string) error)
	// systemsettingDescID is the schema descriptor for id field.
	systemsettingDescID := systemsettingMixinFields0[0].Descriptor()
	// systemsetting.DefaultID holds the default value on creation for the id field.
	systemsetting.DefaultID = systemsettingDescID.Default.(func() string)
	teamMixin := schema.Team{}.Mixin()
	teamMixinFields0 := teamMixin[0].Fields()
	_ = teamMixinFields0
	teamMixinFields1 := teamMixin[1].Fields()
	_ = teamMixinFields1
	teamMixinFields2 := teamMixin[2].Fields()
	_ = teamMixinFields2
	teamFields := schema.Team{}.Fields()
	_ = teamFields
	// teamDescTenantID is the schema descriptor for tenant_id field.
	teamDescTenantID := teamMixinFields1[0].Descriptor()
	// team.DefaultTenantID holds the default value on creation for the tenant_id field.
	team.DefaultTenantID = teamDescTenantID.Default.(string)
	// teamDescCreatedAt is the schema descriptor for created_at field.
	teamDescCreatedAt := teamMixinFields2[0].Descriptor()
	// team.DefaultCreatedAt holds the default value on creation for the created_at field.
	team.DefaultCreatedAt = teamDescCreatedAt.Default.(func() time.Time)
	// teamDescUpdatedAt is the schema descriptor for updated_at field.
	teamDescUpdatedAt := teamMixinFields2[1].Descriptor()
	// team.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	team.DefaultUpdatedAt = teamDescUpdatedAt.Default.(func() time.Time)
	// team.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	team.UpdateDefaultUpdatedAt = teamDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teamDescName is the schema descriptor for name field.
	teamDescName := teamFields[0].Descriptor()
	// team.NameValidator is a validator for the "name" field. It is called by the builders before save.
	team.NameValidator = teamDescName.Validators[0].(func(string) error)
	// teamDescSlug is the schema descriptor for slug field.
	teamDescSlug := teamFields[1].Descriptor()
	// team.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	team.SlugValidator = teamDescSlug.Validators[0].(func(string) error)
	// teamDescOwnerUserID is the schema descriptor for owner_user_id field.
	teamDescOwnerUserID := teamFields[2].Descriptor()
	// team.OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	team.OwnerUserIDValidator = teamDescOwnerUserID.Validators[0].(func(string) error)
	// teamDescID is the schema descriptor for id field.
	teamDescID := teamMixinFields0[0].Descriptor()
	// team.DefaultID holds the default value on creation for the id field.
	team.DefaultID = teamDescID.Default.(func() string)
	teaminviteMixin := schema.TeamInvite{}.Mixin()
	teaminviteMixinFields0 := teaminviteMixin[0].Fields()
	_ = teaminviteMixinFields0
	teaminviteMixinFields1 := teaminviteMixin[1].Fields()
	_ = teaminviteMixinFields1
	teaminviteMixinFields2 := teaminviteMixin[2].Fields()
	_ = teaminviteMixinFields2
	teaminviteFields := schema.TeamInvite{}.Fields()
	_ = teaminviteFields
	// teaminviteDescTenantID is the schema descriptor for tenant_id field.
	teaminviteDescTenantID := teaminviteMixinFields1[0].Descriptor()
	// teaminvite.DefaultTenantID holds the default value on creation for the tenant_id field.
	teaminvite.DefaultTenantID = teaminviteDescTenantID.Default.(string)
	// teaminviteDescCreatedAt is the schema descriptor for created_at field.
	teaminviteDescCreatedAt := teaminviteMixinFields2[0].Descriptor()
	// teaminvite.DefaultCreatedAt holds the default value on creation for the created_at field.
	teaminvite.DefaultCreatedAt = teaminviteDescCreatedAt.Default.(func() time.Time)
	// teaminviteDescUpdatedAt is the schema descriptor for updated_at field.
	teaminviteDescUpdatedAt := teaminviteMixinFields2[1].Descriptor()
	// teaminvite.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teaminvite.DefaultUpdatedAt = teaminviteDescUpdatedAt.Default.(func() time.Time)
	// teaminvite.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teaminvite.UpdateDefaultUpdatedAt = teaminviteDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teaminviteDescTeamID is the schema descriptor for team_id field.
	teaminviteDescTeamID := teaminviteFields[0].Descriptor()
	// teaminvite.TeamIDValidator is a validator for the "team_id" field. It is called by the builders before save.
	teaminvite.TeamIDValidator = teaminviteDescTeamID.Validators[0].(func(string) error)
	// teaminviteDescEmail is the schema descriptor for email field.
	teaminviteDescEmail := teaminviteFields[1].Descriptor()
	// teaminvite.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	teaminvite.EmailValidator = teaminviteDescEmail.Validators[0].(func(string) error)
	// teaminviteDescToken is the schema descriptor for token field.
	teaminviteDescToken := teaminviteFields[2].Descriptor()
	// teaminvite.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	teaminvite.TokenValidator = teaminviteDescToken.Validators[0].(func(string) error)
	// teaminviteDescStatus is the schema descriptor for status field.
	teaminviteDescStatus := teaminviteFields[3].Descriptor()
	// teaminvite.DefaultStatus holds the default value on creation for the status field.
	teaminvite.DefaultStatus = teaminviteDescStatus.Default.(string)
	// teaminviteDescExpiresAt is the schema descriptor for expires_at field.
	teaminviteDescExpiresAt := teaminviteFields[4].Descriptor()
	// teaminvite.DefaultExpiresAt holds the default value on creation for the expires_at field.
	teaminvite.DefaultExpiresAt = teaminviteDescExpiresAt.Default.(func() time.Time)
	// teaminviteDescInvitedBy is the schema descriptor for invited_by field.
	teaminviteDescInvitedBy := teaminviteFields[5].Descriptor()
	// teaminvite.DefaultInvitedBy holds the default value on creation for the invited_by field.
	teaminvite.DefaultInvitedBy = teaminviteDescInvitedBy.Default.(string)
	// teaminviteDescID is the schema descriptor for id field.
	teaminviteDescID := teaminviteMixinFields0[0].Descriptor()
	// teaminvite.DefaultID holds the default value on creation for the id field.
	teaminvite.DefaultID = teaminviteDescID.Default.(func() string)
	teammembershipMixin := schema.TeamMembership{}.Mixin()
	teammembershipMixinFields0 := teammembershipMixin[0].Fields()
	_ = teammembershipMixinFields0
	teammembershipMixinFields1 := teammembershipMixin[1].Fields()
	_ = teammembershipMixinFields1
	teammembershipMixinFields2 := teammembershipMixin[2].Fields()
	_ = teammembershipMixinFields2
	teammembershipFields := schema.TeamMembership{}.Fields()
	_ = teammembershipFields
	// teammembershipDescTenantID is the schema descriptor for tenant_id field.
	teammembershipDescTenantID := teammembershipMixinFields1[0].Descriptor()
	// teammembership.DefaultTenantID holds the default value on creation for the tenant_id field.
	teammembership.DefaultTenantID = teammembershipDescTenantID.Default.(string)
	// teammembershipDescCreatedAt is the schema descriptor for created_at field.
	teammembershipDescCreatedAt := teammembershipMixinFields2[0].Descriptor()
	// teammembership.DefaultCreatedAt holds the default value on creation for the created_at field.
	teammembership.DefaultCreatedAt = teammembershipDescCreatedAt.Default.(func() time.Time)
	// teammembershipDescUpdatedAt is the schema descriptor for updated_at field.
	teammembershipDescUpdatedAt := teammembershipMixinFields2[1].Descriptor()
	// teammembership.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teammembership.DefaultUpdatedAt = teammembershipDescUpdatedAt.Default.(func() time.Time)
	// teammembership.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teammembership.UpdateDefaultUpdatedAt = teammembershipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teammembershipDescTeamID is the schema descriptor for team_id field.
	teammembershipDescTeamID := teammembershipFields[0].Descriptor()
	// teammembership.TeamIDValidator is a validator for the "team_id" field. It is called by the builders before save.
	teammembership.TeamIDValidator = teammembershipDescTeamID.Validators[0].(func(string) error)
	// teammembershipDescUserID is the schema descriptor for user_id field.
	teammembershipDescUserID := teammembershipFields[1].Descriptor()
	// teammembership.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	teammembership.UserIDValidator = teammembershipDescUserID.Validators[0].(func(string) error)
	// teammembershipDescRole is the schema descriptor for role field.
	teammembershipDescRole := teammembershipFields[2].Descriptor()
	// teammembership.DefaultRole holds the default value on creation for the role field.
	teammembership.DefaultRole = teammembershipDescRole.Default.(string)
	// teammembershipDescID is the schema descriptor for id field.
	teammembershipDescID := teammembershipMixinFields0[0].Descriptor()
	// teammembership.DefaultID holds the default value on creation for the id field.
	teammembership.DefaultID = teammembershipDescID.Default.(func() string)
	teamroleMixin := schema.TeamRole{}.Mixin()
	teamroleMixinFields0 := teamroleMixin[0].Fields()
	_ = teamroleMixinFields0
	teamroleMixinFields1 := teamroleMixin[1].Fields()
	_ = teamroleMixinFields1
	teamroleMixinFields2 := teamroleMixin[2].Fields()
	_ = teamroleMixinFields2
	teamroleFields := schema.TeamRole{}.Fields()
	_ = teamroleFields
	// teamroleDescTenantID is the schema descriptor for tenant_id field.
	teamroleDescTenantID := teamroleMixinFields1[0].Descriptor()
	// teamrole.DefaultTenantID holds the default value on creation for the tenant_id field.
	teamrole.DefaultTenantID = teamroleDescTenantID.Default.(string)
	// teamroleDescCreatedAt is the schema descriptor for created_at field.
	teamroleDescCreatedAt := teamroleMixinFields2[0].Descriptor()
	// teamrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamrole.DefaultCreatedAt = teamroleDescCreatedAt.Default.(func() time.Time)
	// teamroleDescUpdatedAt is the schema descriptor for updated_at field.
	teamroleDescUpdatedAt := teamroleMixinFields2[1].Descriptor()
	// teamrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamrole.DefaultUpdatedAt = teamroleDescUpdatedAt.Default.(func() time.Time)
	// teamrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamrole.UpdateDefaultUpdatedAt = teamroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teamroleDescTeamID is the schema descriptor for team_id field.
	teamroleDescTeamID := teamroleFields[0].Descriptor()
	// teamrole.TeamIDValidator is a validator for the "team_id" field. It is called by the builders before save.
	teamrole.TeamIDValidator = teamroleDescTeamID.Validators[0].(func(string) error)
	// teamroleDescRoleID is the schema descriptor for role_id field.
	teamroleDescRoleID := teamroleFields[1].Descriptor()
	// teamrole.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	teamrole.RoleIDValidator = teamroleDescRoleID.Validators[0].(func(string) error)
	// teamroleDescName is the schema descriptor for name field.
	teamroleDescName := teamroleFields[2].Descriptor()
	// teamrole.NameValidator is a validator for the "name" field. It is called by the builders before save.
	teamrole.NameValidator = teamroleDescName.Validators[0].(func(string) error)
	// teamroleDescDescription is the schema descriptor for description field.
	teamroleDescDescription := teamroleFields[3].Descriptor()
	// teamrole.DefaultDescription holds the default value on creation for the description field.
	teamrole.DefaultDescription = teamroleDescDescription.Default.(string)
	// teamroleDescPermissions is the schema descriptor for permissions field.
	teamroleDescPermissions := teamroleFields[4].Descriptor()
	// teamrole.DefaultPermissions holds the default value on creation for the permissions field.
	teamrole.DefaultPermissions = teamroleDescPermissions.Default.([]string)
	// teamroleDescID is the schema descriptor for id field.
	teamroleDescID := teamroleMixinFields0[0].Descriptor()
	// teamrole.DefaultID holds the default value on creation for the id field.
	teamrole.DefaultID = teamroleDescID.Default.(func() string)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userMixinFields2 := userMixin[2].Fields()
	_ = userMixinFields2
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTenantID is the schema descriptor for tenant_id field.
	userDescTenantID := userMixinFields1[0].Descriptor()
	// user.DefaultTenantID holds the default value on creation for the tenant_id field.
	user.DefaultTenantID = userDescTenantID.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields2[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields2[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[2].Descriptor()
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = userDescDisplayName.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[3].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[4].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
	userrolebindingMixin := schema.UserRoleBinding{}.Mixin()
	userrolebindingMixinFields0 := userrolebindingMixin[0].Fields()
	_ = userrolebindingMixinFields0
	userrolebindingMixinFields1 := userrolebindingMixin[1].Fields()
	_ = userrolebindingMixinFields1
	userrolebindingMixinFields2 := userrolebindingMixin[2].Fields()
	_ = userrolebindingMixinFields2
	userrolebindingFields := schema.UserRoleBinding{}.Fields()
	_ = userrolebindingFields
	// userrolebindingDescTenantID is the schema descriptor for tenant_id field.
	userrolebindingDescTenantID := userrolebindingMixinFields1[0].Descriptor()
	// userrolebinding.DefaultTenantID holds the default value on creation for the tenant_id field.
	userrolebinding.DefaultTenantID = userrolebindingDescTenantID.Default.(string)
	// userrolebindingDescCreatedAt is the schema descriptor for created_at field.
	userrolebindingDescCreatedAt := userrolebindingMixinFields2[0].Descriptor()
	// userrolebinding.DefaultCreatedAt holds the default value on creation for the created_at field.
	userrolebinding.DefaultCreatedAt = userrolebindingDescCreatedAt.Default.(func() time.Time)
	// userrolebindingDescUpdatedAt is the schema descriptor for updated_at field.
	userrolebindingDescUpdatedAt := userrolebindingMixinFields2[1].Descriptor()
	// userrolebinding.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userrolebinding.DefaultUpdatedAt = userrolebindingDescUpdatedAt.Default.(func() time.Time)
	// userrolebinding.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userrolebinding.UpdateDefaultUpdatedAt = userrolebindingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userrolebindingDescUserID is the schema descriptor for user_id field.
	userrolebindingDescUserID := userrolebindingFields[0].Descriptor()
	// userrolebinding.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userrolebinding.UserIDValidator = userrolebindingDescUserID.Validators[0].(func(string) error)
	// userrolebindingDescRoleID is the schema descriptor for role_id field.
	userrolebindingDescRoleID := userrolebindingFields[1].Descriptor()
	// userrolebinding.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	userrolebinding.RoleIDValidator = userrolebindingDescRoleID.Validators[0].(func(string) error)
	// userrolebindingDescID is the schema descriptor for id field.
	userrolebindingDescID := userrolebindingMixinFields0[0].Descriptor()
	// userrolebinding.DefaultID holds the default value on creation for the id field.
	userrolebinding.DefaultID = userrolebindingDescID.Default.(func() string)
}
