// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/night/go-astro-template/apps/api/ent/team"
	"github.com/night/go-astro-template/apps/api/ent/teaminvite"
)

// TeamInviteCreate is the builder for creating a TeamInvite entity.
type TeamInviteCreate struct {
	config
	mutation *TeamInviteMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *TeamInviteCreate) SetTenantID(v string) *TeamInviteCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TeamInviteCreate) SetNillableTenantID(v *string) *TeamInviteCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamInviteCreate) SetCreatedAt(v time.Time) *TeamInviteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamInviteCreate) SetNillableCreatedAt(v *time.Time) *TeamInviteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamInviteCreate) SetUpdatedAt(v time.Time) *TeamInviteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamInviteCreate) SetNillableUpdatedAt(v *time.Time) *TeamInviteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *TeamInviteCreate) SetTeamID(v string) *TeamInviteCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *TeamInviteCreate) SetEmail(v string) *TeamInviteCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *TeamInviteCreate) SetToken(v string) *TeamInviteCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TeamInviteCreate) SetStatus(v string) *TeamInviteCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TeamInviteCreate) SetNillableStatus(v *string) *TeamInviteCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TeamInviteCreate) SetExpiresAt(v time.Time) *TeamInviteCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *TeamInviteCreate) SetNillableExpiresAt(v *time.Time) *TeamInviteCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetInvitedBy sets the "invited_by" field.
func (_c *TeamInviteCreate) SetInvitedBy(v string) *TeamInviteCreate {
	_c.mutation.SetInvitedBy(v)
	return _c
}

// SetNillableInvitedBy sets the "invited_by" field if the given value is not nil.
func (_c *TeamInviteCreate) SetNillableInvitedBy(v *string) *TeamInviteCreate {
	if v != nil {
		_c.SetInvitedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TeamInviteCreate) SetID(v string) *TeamInviteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TeamInviteCreate) SetNillableID(v *string) *TeamInviteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamInviteCreate) SetTeam(v *Team) *TeamInviteCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the TeamInviteMutation object of the builder.
func (_c *TeamInviteCreate) Mutation() *TeamInviteMutation {
	return _c.mutation
}

// Save creates the TeamInvite in the database.
func (_c *TeamInviteCreate) Save(ctx context.Context) (*TeamInvite, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamInviteCreate) SaveX(ctx context.Context) *TeamInvite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamInviteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamInviteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamInviteCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := teaminvite.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teaminvite.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := teaminvite.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := teaminvite.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		v := teaminvite.DefaultExpiresAt()
		_c.mutation.SetExpiresAt(v)
	}
	if _, ok := _c.mutation.InvitedBy(); !ok {
		v := teaminvite.DefaultInvitedBy
		_c.mutation.SetInvitedBy(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := teaminvite.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamInviteCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TeamInvite.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamInvite.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TeamInvite.updated_at"`)}
	}
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamInvite.team_id"`)}
	}
	if v, ok := _c.mutation.TeamID(); ok {
		if err := teaminvite.TeamIDValidator(v); err != nil {
			return &ValidationError{Name: "team_id", err: fmt.Errorf(`ent: validator failed for field "TeamInvite.team_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "TeamInvite.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := teaminvite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TeamInvite.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "TeamInvite.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := teaminvite.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "TeamInvite.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TeamInvite.status"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "TeamInvite.expires_at"`)}
	}
	if _, ok := _c.mutation.InvitedBy(); !ok {
		return &ValidationError{Name: "invited_by", err: errors.New(`ent: missing required field "TeamInvite.invited_by"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamInvite.team"`)}
	}
	return nil
}

func (_c *TeamInviteCreate) sqlSave(ctx context.Context) (*TeamInvite, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TeamInvite.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamInviteCreate) createSpec() (*TeamInvite, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamInvite{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teaminvite.Table, sqlgraph.NewFieldSpec(teaminvite.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(teaminvite.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teaminvite.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(teaminvite.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(teaminvite.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(teaminvite.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(teaminvite.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(teaminvite.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.InvitedBy(); ok {
		_spec.SetField(teaminvite.FieldInvitedBy, field.TypeString, value)
		_node.InvitedBy = value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvite.TeamTable,
			Columns: []string{teaminvite.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TeamInviteCreateBulk is the builder for creating many TeamInvite entities in bulk.
type TeamInviteCreateBulk struct {
	config
	err      error
	builders []*TeamInviteCreate
}

// Save creates the TeamInvite entities in the database.
func (_c *TeamInviteCreateBulk) Save(ctx context.Context) ([]*TeamInvite, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamInvite, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamInviteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamInviteCreateBulk) SaveX(ctx context.Context) []*TeamInvite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamInviteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamInviteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
