// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
	"github.com/night/go-astro-template/apps/api/ent/team"
	"github.com/night/go-astro-template/apps/api/ent/teaminvite"
)

// TeamInviteUpdate is the builder for updating TeamInvite entities.
type TeamInviteUpdate struct {
	config
	hooks    []Hook
	mutation *TeamInviteMutation
}

// Where appends a list predicates to the TeamInviteUpdate builder.
func (_u *TeamInviteUpdate) Where(ps ...predicate.TeamInvite) *TeamInviteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamInviteUpdate) SetUpdatedAt(v time.Time) *TeamInviteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamInviteUpdate) SetTeamID(v string) *TeamInviteUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamInviteUpdate) SetNillableTeamID(v *string) *TeamInviteUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *TeamInviteUpdate) SetEmail(v string) *TeamInviteUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TeamInviteUpdate) SetNillableEmail(v *string) *TeamInviteUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *TeamInviteUpdate) SetToken(v string) *TeamInviteUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TeamInviteUpdate) SetNillableToken(v *string) *TeamInviteUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamInviteUpdate) SetStatus(v string) *TeamInviteUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamInviteUpdate) SetNillableStatus(v *string) *TeamInviteUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TeamInviteUpdate) SetExpiresAt(v time.Time) *TeamInviteUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TeamInviteUpdate) SetNillableExpiresAt(v *time.Time) *TeamInviteUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetInvitedBy sets the "invited_by" field.
func (_u *TeamInviteUpdate) SetInvitedBy(v string) *TeamInviteUpdate {
	_u.mutation.SetInvitedBy(v)
	return _u
}

// SetNillableInvitedBy sets the "invited_by" field if the given value is not nil.
func (_u *TeamInviteUpdate) SetNillableInvitedBy(v *string) *TeamInviteUpdate {
	if v != nil {
		_u.SetInvitedBy(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamInviteUpdate) SetTeam(v *Team) *TeamInviteUpdate {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamInviteMutation object of the builder.
func (_u *TeamInviteUpdate) Mutation() *TeamInviteMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamInviteUpdate) ClearTeam() *TeamInviteUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamInviteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamInviteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamInviteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamInviteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamInviteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teaminvite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamInviteUpdate) check() error {
	if v, ok := _u.mutation.TeamID(); ok {
		if err := teaminvite.TeamIDValidator(v); err != nil {
			return &ValidationError{Name: "team_id", err: fmt.Errorf(`ent: validator failed for field "TeamInvite.team_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := teaminvite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TeamInvite.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := teaminvite.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "TeamInvite.token": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamInvite.team"`)
	}
	return nil
}

func (_u *TeamInviteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teaminvite.Table, teaminvite.Columns, sqlgraph.NewFieldSpec(teaminvite.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teaminvite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(teaminvite.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(teaminvite.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teaminvite.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(teaminvite.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.InvitedBy(); ok {
		_spec.SetField(teaminvite.FieldInvitedBy, field.TypeString, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvite.TeamTable,
			Columns: []string{teaminvite.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvite.TeamTable,
			Columns: []string{teaminvite.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teaminvite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamInviteUpdateOne is the builder for updating a single TeamInvite entity.
type TeamInviteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamInviteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamInviteUpdateOne) SetUpdatedAt(v time.Time) *TeamInviteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamInviteUpdateOne) SetTeamID(v string) *TeamInviteUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamInviteUpdateOne) SetNillableTeamID(v *string) *TeamInviteUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *TeamInviteUpdateOne) SetEmail(v string) *TeamInviteUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TeamInviteUpdateOne) SetNillableEmail(v *string) *TeamInviteUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *TeamInviteUpdateOne) SetToken(v string) *TeamInviteUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TeamInviteUpdateOne) SetNillableToken(v *string) *TeamInviteUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamInviteUpdateOne) SetStatus(v string) *TeamInviteUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamInviteUpdateOne) SetNillableStatus(v *string) *TeamInviteUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TeamInviteUpdateOne) SetExpiresAt(v time.Time) *TeamInviteUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TeamInviteUpdateOne) SetNillableExpiresAt(v *time.Time) *TeamInviteUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetInvitedBy sets the "invited_by" field.
func (_u *TeamInviteUpdateOne) SetInvitedBy(v string) *TeamInviteUpdateOne {
	_u.mutation.SetInvitedBy(v)
	return _u
}

// SetNillableInvitedBy sets the "invited_by" field if the given value is not nil.
func (_u *TeamInviteUpdateOne) SetNillableInvitedBy(v *string) *TeamInviteUpdateOne {
	if v != nil {
		_u.SetInvitedBy(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamInviteUpdateOne) SetTeam(v *Team) *TeamInviteUpdateOne {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamInviteMutation object of the builder.
func (_u *TeamInviteUpdateOne) Mutation() *TeamInviteMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamInviteUpdateOne) ClearTeam() *TeamInviteUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// Where appends a list predicates to the TeamInviteUpdate builder.
func (_u *TeamInviteUpdateOne) Where(ps ...predicate.TeamInvite) *TeamInviteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamInviteUpdateOne) Select(field string, fields ...string) *TeamInviteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamInvite entity.
func (_u *TeamInviteUpdateOne) Save(ctx context.Context) (*TeamInvite, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamInviteUpdateOne) SaveX(ctx context.Context) *TeamInvite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamInviteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamInviteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamInviteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teaminvite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamInviteUpdateOne) check() error {
	if v, ok := _u.mutation.TeamID(); ok {
		if err := teaminvite.TeamIDValidator(v); err != nil {
			return &ValidationError{Name: "team_id", err: fmt.Errorf(`ent: validator failed for field "TeamInvite.team_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := teaminvite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TeamInvite.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := teaminvite.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "TeamInvite.token": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamInvite.team"`)
	}
	return nil
}

func (_u *TeamInviteUpdateOne) sqlSave(ctx context.Context) (_node *TeamInvite, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teaminvite.Table, teaminvite.Columns, sqlgraph.NewFieldSpec(teaminvite.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamInvite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teaminvite.FieldID)
		for _, f := range fields {
			if !teaminvite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teaminvite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teaminvite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(teaminvite.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(teaminvite.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teaminvite.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(teaminvite.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.InvitedBy(); ok {
		_spec.SetField(teaminvite.FieldInvitedBy, field.TypeString, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvite.TeamTable,
			Columns: []string{teaminvite.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvite.TeamTable,
			Columns: []string{teaminvite.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamInvite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teaminvite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
