// Code generated by ent, DO NOT EDIT.

package maillog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// TemplateKey applies equality check predicate on the "template_key" field. It's identical to TemplateKeyEQ.
func TemplateKey(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldTemplateKey, v))
}

// Recipient applies equality check predicate on the "recipient" field. It's identical to RecipientEQ.
func Recipient(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldRecipient, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldSubject, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldStatus, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldErrorMessage, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldSentAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContainsFold(FieldTenantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// TemplateKeyEQ applies the EQ predicate on the "template_key" field.
func TemplateKeyEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldTemplateKey, v))
}

// TemplateKeyNEQ applies the NEQ predicate on the "template_key" field.
func TemplateKeyNEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNEQ(FieldTemplateKey, v))
}

// TemplateKeyIn applies the In predicate on the "template_key" field.
func TemplateKeyIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldIn(FieldTemplateKey, vs...))
}

// TemplateKeyNotIn applies the NotIn predicate on the "template_key" field.
func TemplateKeyNotIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNotIn(FieldTemplateKey, vs...))
}

// TemplateKeyGT applies the GT predicate on the "template_key" field.
func TemplateKeyGT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGT(FieldTemplateKey, v))
}

// TemplateKeyGTE applies the GTE predicate on the "template_key" field.
func TemplateKeyGTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGTE(FieldTemplateKey, v))
}

// TemplateKeyLT applies the LT predicate on the "template_key" field.
func TemplateKeyLT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLT(FieldTemplateKey, v))
}

// TemplateKeyLTE applies the LTE predicate on the "template_key" field.
func TemplateKeyLTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLTE(FieldTemplateKey, v))
}

// TemplateKeyContains applies the Contains predicate on the "template_key" field.
func TemplateKeyContains(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContains(FieldTemplateKey, v))
}

// TemplateKeyHasPrefix applies the HasPrefix predicate on the "template_key" field.
func TemplateKeyHasPrefix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasPrefix(FieldTemplateKey, v))
}

// TemplateKeyHasSuffix applies the HasSuffix predicate on the "template_key" field.
func TemplateKeyHasSuffix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasSuffix(FieldTemplateKey, v))
}

// TemplateKeyEqualFold applies the EqualFold predicate on the "template_key" field.
func TemplateKeyEqualFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEqualFold(FieldTemplateKey, v))
}

// TemplateKeyContainsFold applies the ContainsFold predicate on the "template_key" field.
func TemplateKeyContainsFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContainsFold(FieldTemplateKey, v))
}

// RecipientEQ applies the EQ predicate on the "recipient" field.
func RecipientEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldRecipient, v))
}

// RecipientNEQ applies the NEQ predicate on the "recipient" field.
func RecipientNEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNEQ(FieldRecipient, v))
}

// RecipientIn applies the In predicate on the "recipient" field.
func RecipientIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldIn(FieldRecipient, vs...))
}

// RecipientNotIn applies the NotIn predicate on the "recipient" field.
func RecipientNotIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNotIn(FieldRecipient, vs...))
}

// RecipientGT applies the GT predicate on the "recipient" field.
func RecipientGT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGT(FieldRecipient, v))
}

// RecipientGTE applies the GTE predicate on the "recipient" field.
func RecipientGTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGTE(FieldRecipient, v))
}

// RecipientLT applies the LT predicate on the "recipient" field.
func RecipientLT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLT(FieldRecipient, v))
}

// RecipientLTE applies the LTE predicate on the "recipient" field.
func RecipientLTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLTE(FieldRecipient, v))
}

// RecipientContains applies the Contains predicate on the "recipient" field.
func RecipientContains(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContains(FieldRecipient, v))
}

// RecipientHasPrefix applies the HasPrefix predicate on the "recipient" field.
func RecipientHasPrefix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasPrefix(FieldRecipient, v))
}

// RecipientHasSuffix applies the HasSuffix predicate on the "recipient" field.
func RecipientHasSuffix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasSuffix(FieldRecipient, v))
}

// RecipientEqualFold applies the EqualFold predicate on the "recipient" field.
func RecipientEqualFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEqualFold(FieldRecipient, v))
}

// RecipientContainsFold applies the ContainsFold predicate on the "recipient" field.
func RecipientContainsFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContainsFold(FieldRecipient, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContainsFold(FieldSubject, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.MailLog {
	return predicate.MailLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.MailLog {
	return predicate.MailLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.MailLog {
	return predicate.MailLog(sql.FieldLTE(FieldSentAt, v))
}

// SentAtIsNil applies the IsNil predicate on the "sent_at" field.
func SentAtIsNil() predicate.MailLog {
	return predicate.MailLog(sql.FieldIsNull(FieldSentAt))
}

// SentAtNotNil applies the NotNil predicate on the "sent_at" field.
func SentAtNotNil() predicate.MailLog {
	return predicate.MailLog(sql.FieldNotNull(FieldSentAt))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.MailLog {
	return predicate.MailLog(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.MailLog {
	return predicate.MailLog(sql.FieldNotNull(FieldPayload))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MailLog) predicate.MailLog {
	return predicate.MailLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MailLog) predicate.MailLog {
	return predicate.MailLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MailLog) predicate.MailLog {
	return predicate.MailLog(sql.NotPredicates(p))
}
