// Code generated by ent, DO NOT EDIT.

package blogtranslation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/night/go-astro-template/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// BlogPostID applies equality check predicate on the "blog_post_id" field. It's identical to BlogPostIDEQ.
func BlogPostID(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldBlogPostID, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldLanguage, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldTitle, v))
}

// Excerpt applies equality check predicate on the "excerpt" field. It's identical to ExcerptEQ.
func Excerpt(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldExcerpt, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldContent, v))
}

// MetaTitle applies equality check predicate on the "meta_title" field. It's identical to MetaTitleEQ.
func MetaTitle(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldMetaTitle, v))
}

// MetaDescription applies equality check predicate on the "meta_description" field. It's identical to MetaDescriptionEQ.
func MetaDescription(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldMetaDescription, v))
}

// Keywords applies equality check predicate on the "keywords" field. It's identical to KeywordsEQ.
func Keywords(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldKeywords, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContainsFold(FieldTenantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldUpdatedAt, v))
}

// BlogPostIDEQ applies the EQ predicate on the "blog_post_id" field.
func BlogPostIDEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldBlogPostID, v))
}

// BlogPostIDNEQ applies the NEQ predicate on the "blog_post_id" field.
func BlogPostIDNEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldBlogPostID, v))
}

// BlogPostIDIn applies the In predicate on the "blog_post_id" field.
func BlogPostIDIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldBlogPostID, vs...))
}

// BlogPostIDNotIn applies the NotIn predicate on the "blog_post_id" field.
func BlogPostIDNotIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldBlogPostID, vs...))
}

// BlogPostIDGT applies the GT predicate on the "blog_post_id" field.
func BlogPostIDGT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldBlogPostID, v))
}

// BlogPostIDGTE applies the GTE predicate on the "blog_post_id" field.
func BlogPostIDGTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldBlogPostID, v))
}

// BlogPostIDLT applies the LT predicate on the "blog_post_id" field.
func BlogPostIDLT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldBlogPostID, v))
}

// BlogPostIDLTE applies the LTE predicate on the "blog_post_id" field.
func BlogPostIDLTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldBlogPostID, v))
}

// BlogPostIDContains applies the Contains predicate on the "blog_post_id" field.
func BlogPostIDContains(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContains(FieldBlogPostID, v))
}

// BlogPostIDHasPrefix applies the HasPrefix predicate on the "blog_post_id" field.
func BlogPostIDHasPrefix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasPrefix(FieldBlogPostID, v))
}

// BlogPostIDHasSuffix applies the HasSuffix predicate on the "blog_post_id" field.
func BlogPostIDHasSuffix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasSuffix(FieldBlogPostID, v))
}

// BlogPostIDEqualFold applies the EqualFold predicate on the "blog_post_id" field.
func BlogPostIDEqualFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEqualFold(FieldBlogPostID, v))
}

// BlogPostIDContainsFold applies the ContainsFold predicate on the "blog_post_id" field.
func BlogPostIDContainsFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContainsFold(FieldBlogPostID, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContainsFold(FieldLanguage, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContainsFold(FieldTitle, v))
}

// ExcerptEQ applies the EQ predicate on the "excerpt" field.
func ExcerptEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldExcerpt, v))
}

// ExcerptNEQ applies the NEQ predicate on the "excerpt" field.
func ExcerptNEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldExcerpt, v))
}

// ExcerptIn applies the In predicate on the "excerpt" field.
func ExcerptIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldExcerpt, vs...))
}

// ExcerptNotIn applies the NotIn predicate on the "excerpt" field.
func ExcerptNotIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldExcerpt, vs...))
}

// ExcerptGT applies the GT predicate on the "excerpt" field.
func ExcerptGT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldExcerpt, v))
}

// ExcerptGTE applies the GTE predicate on the "excerpt" field.
func ExcerptGTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldExcerpt, v))
}

// ExcerptLT applies the LT predicate on the "excerpt" field.
func ExcerptLT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldExcerpt, v))
}

// ExcerptLTE applies the LTE predicate on the "excerpt" field.
func ExcerptLTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldExcerpt, v))
}

// ExcerptContains applies the Contains predicate on the "excerpt" field.
func ExcerptContains(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContains(FieldExcerpt, v))
}

// ExcerptHasPrefix applies the HasPrefix predicate on the "excerpt" field.
func ExcerptHasPrefix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasPrefix(FieldExcerpt, v))
}

// ExcerptHasSuffix applies the HasSuffix predicate on the "excerpt" field.
func ExcerptHasSuffix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasSuffix(FieldExcerpt, v))
}

// ExcerptIsNil applies the IsNil predicate on the "excerpt" field.
func ExcerptIsNil() predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIsNull(FieldExcerpt))
}

// ExcerptNotNil applies the NotNil predicate on the "excerpt" field.
func ExcerptNotNil() predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotNull(FieldExcerpt))
}

// ExcerptEqualFold applies the EqualFold predicate on the "excerpt" field.
func ExcerptEqualFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEqualFold(FieldExcerpt, v))
}

// ExcerptContainsFold applies the ContainsFold predicate on the "excerpt" field.
func ExcerptContainsFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContainsFold(FieldExcerpt, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContainsFold(FieldContent, v))
}

// MetaTitleEQ applies the EQ predicate on the "meta_title" field.
func MetaTitleEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldMetaTitle, v))
}

// MetaTitleNEQ applies the NEQ predicate on the "meta_title" field.
func MetaTitleNEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldMetaTitle, v))
}

// MetaTitleIn applies the In predicate on the "meta_title" field.
func MetaTitleIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldMetaTitle, vs...))
}

// MetaTitleNotIn applies the NotIn predicate on the "meta_title" field.
func MetaTitleNotIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldMetaTitle, vs...))
}

// MetaTitleGT applies the GT predicate on the "meta_title" field.
func MetaTitleGT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldMetaTitle, v))
}

// MetaTitleGTE applies the GTE predicate on the "meta_title" field.
func MetaTitleGTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldMetaTitle, v))
}

// MetaTitleLT applies the LT predicate on the "meta_title" field.
func MetaTitleLT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldMetaTitle, v))
}

// MetaTitleLTE applies the LTE predicate on the "meta_title" field.
func MetaTitleLTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldMetaTitle, v))
}

// MetaTitleContains applies the Contains predicate on the "meta_title" field.
func MetaTitleContains(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContains(FieldMetaTitle, v))
}

// MetaTitleHasPrefix applies the HasPrefix predicate on the "meta_title" field.
func MetaTitleHasPrefix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasPrefix(FieldMetaTitle, v))
}

// MetaTitleHasSuffix applies the HasSuffix predicate on the "meta_title" field.
func MetaTitleHasSuffix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasSuffix(FieldMetaTitle, v))
}

// MetaTitleIsNil applies the IsNil predicate on the "meta_title" field.
func MetaTitleIsNil() predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIsNull(FieldMetaTitle))
}

// MetaTitleNotNil applies the NotNil predicate on the "meta_title" field.
func MetaTitleNotNil() predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotNull(FieldMetaTitle))
}

// MetaTitleEqualFold applies the EqualFold predicate on the "meta_title" field.
func MetaTitleEqualFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEqualFold(FieldMetaTitle, v))
}

// MetaTitleContainsFold applies the ContainsFold predicate on the "meta_title" field.
func MetaTitleContainsFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContainsFold(FieldMetaTitle, v))
}

// MetaDescriptionEQ applies the EQ predicate on the "meta_description" field.
func MetaDescriptionEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldMetaDescription, v))
}

// MetaDescriptionNEQ applies the NEQ predicate on the "meta_description" field.
func MetaDescriptionNEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldMetaDescription, v))
}

// MetaDescriptionIn applies the In predicate on the "meta_description" field.
func MetaDescriptionIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldMetaDescription, vs...))
}

// MetaDescriptionNotIn applies the NotIn predicate on the "meta_description" field.
func MetaDescriptionNotIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldMetaDescription, vs...))
}

// MetaDescriptionGT applies the GT predicate on the "meta_description" field.
func MetaDescriptionGT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldMetaDescription, v))
}

// MetaDescriptionGTE applies the GTE predicate on the "meta_description" field.
func MetaDescriptionGTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldMetaDescription, v))
}

// MetaDescriptionLT applies the LT predicate on the "meta_description" field.
func MetaDescriptionLT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldMetaDescription, v))
}

// MetaDescriptionLTE applies the LTE predicate on the "meta_description" field.
func MetaDescriptionLTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldMetaDescription, v))
}

// MetaDescriptionContains applies the Contains predicate on the "meta_description" field.
func MetaDescriptionContains(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContains(FieldMetaDescription, v))
}

// MetaDescriptionHasPrefix applies the HasPrefix predicate on the "meta_description" field.
func MetaDescriptionHasPrefix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasPrefix(FieldMetaDescription, v))
}

// MetaDescriptionHasSuffix applies the HasSuffix predicate on the "meta_description" field.
func MetaDescriptionHasSuffix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasSuffix(FieldMetaDescription, v))
}

// MetaDescriptionIsNil applies the IsNil predicate on the "meta_description" field.
func MetaDescriptionIsNil() predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIsNull(FieldMetaDescription))
}

// MetaDescriptionNotNil applies the NotNil predicate on the "meta_description" field.
func MetaDescriptionNotNil() predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotNull(FieldMetaDescription))
}

// MetaDescriptionEqualFold applies the EqualFold predicate on the "meta_description" field.
func MetaDescriptionEqualFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEqualFold(FieldMetaDescription, v))
}

// MetaDescriptionContainsFold applies the ContainsFold predicate on the "meta_description" field.
func MetaDescriptionContainsFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContainsFold(FieldMetaDescription, v))
}

// KeywordsEQ applies the EQ predicate on the "keywords" field.
func KeywordsEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEQ(FieldKeywords, v))
}

// KeywordsNEQ applies the NEQ predicate on the "keywords" field.
func KeywordsNEQ(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNEQ(FieldKeywords, v))
}

// KeywordsIn applies the In predicate on the "keywords" field.
func KeywordsIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIn(FieldKeywords, vs...))
}

// KeywordsNotIn applies the NotIn predicate on the "keywords" field.
func KeywordsNotIn(vs ...string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotIn(FieldKeywords, vs...))
}

// KeywordsGT applies the GT predicate on the "keywords" field.
func KeywordsGT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGT(FieldKeywords, v))
}

// KeywordsGTE applies the GTE predicate on the "keywords" field.
func KeywordsGTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldGTE(FieldKeywords, v))
}

// KeywordsLT applies the LT predicate on the "keywords" field.
func KeywordsLT(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLT(FieldKeywords, v))
}

// KeywordsLTE applies the LTE predicate on the "keywords" field.
func KeywordsLTE(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldLTE(FieldKeywords, v))
}

// KeywordsContains applies the Contains predicate on the "keywords" field.
func KeywordsContains(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContains(FieldKeywords, v))
}

// KeywordsHasPrefix applies the HasPrefix predicate on the "keywords" field.
func KeywordsHasPrefix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasPrefix(FieldKeywords, v))
}

// KeywordsHasSuffix applies the HasSuffix predicate on the "keywords" field.
func KeywordsHasSuffix(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldHasSuffix(FieldKeywords, v))
}

// KeywordsIsNil applies the IsNil predicate on the "keywords" field.
func KeywordsIsNil() predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldIsNull(FieldKeywords))
}

// KeywordsNotNil applies the NotNil predicate on the "keywords" field.
func KeywordsNotNil() predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldNotNull(FieldKeywords))
}

// KeywordsEqualFold applies the EqualFold predicate on the "keywords" field.
func KeywordsEqualFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldEqualFold(FieldKeywords, v))
}

// KeywordsContainsFold applies the ContainsFold predicate on the "keywords" field.
func KeywordsContainsFold(v string) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.FieldContainsFold(FieldKeywords, v))
}

// HasBlogPost applies the HasEdge predicate on the "blog_post" edge.
func HasBlogPost() predicate.BlogTranslation {
	return predicate.BlogTranslation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BlogPostTable, BlogPostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlogPostWith applies the HasEdge predicate on the "blog_post" edge with a given conditions (other predicates).
func HasBlogPostWith(preds ...predicate.BlogPost) predicate.BlogTranslation {
	return predicate.BlogTranslation(func(s *sql.Selector) {
		step := newBlogPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BlogTranslation) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BlogTranslation) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BlogTranslation) predicate.BlogTranslation {
	return predicate.BlogTranslation(sql.NotPredicates(p))
}
